### ISSUE TITLE
Add Leo reductions for right-recursive grammars

### ISSUE THREAD

**Issue by aredridel** [Hardmath123/nearley#10]
Using the tweaks to the algorithm from Leo, Joop "A general context-free parsing algorithm running in linear time on every LR(k) grammar without using lookahead", Theoretical Computer Science, Vol 82 (1991)

**Comment by Hardmath123** [comment]
Two years later… I had some free time, so I went ahead and did it. It was tricky stuff, but satisfying. Thanks for the pointers (and also all your help with nearley back when it was a young project)!

**Comment by aredridel** [comment]
Yay!
