### ISSUE TITLE
Unnecessary "new" in nearleyc

### ISSUE THREAD

**Issue by moll** [Hardmath123/nearley#104]
Hey again,

Noticed an unnecessary `new` on https://github.com/Hardmath123/nearley/blob/master/bin/nearleyc.js#L42.

**Comment by Hardmath123** [comment]
Mmmm, weird, thanks for the tip. Would you like to PR a fix?

**Comment by moll** [comment]
I wish I could, but I have hard enough of a time to get around to the plethora of my own OSS. Suggesting things through GitHub issues can do. :D

**Comment by nanalan** [comment]
This can be closed as #120 was merged.
