### ISSUE TITLE
Request: Live parser playground

### ISSUE THREAD

**Issue by matthew-dean** [Hardmath123/nearley#106]
Would it be possible to set up a page like http://pegjs.org/online as a way to learn how to make grammar for Nearley?

(Double bonus: suggested optimizations.)

**Comment by Hardmath123** [comment]
Sure, we used to have a demo but it was a bit glitchy. Does anyone want to take the lead on implementing this? It should be easy-peasy.

**Comment by Hardmath123** [comment]
Duplicate of #37, #68.

**Comment by Hardmath123** [comment]
(Last update for tonight: see `index.html` and `www/main.js` for existing progress on this. Really, all that's left is for someone to hack together a frontend with some sort of text box and a couple of buttons.)

**Comment by matthew-dean** [comment]
Ah.

**Comment by Hardmath123** [comment]
See http://omrelli.ug/nearley-playground/.
