### ISSUE TITLE
Capability to completely skip certain token types.

### ISSUE THREAD

**Issue by bd82** [Hardmath123/nearley#110]
Is this possible with nearley? should it be?
The use case is to completely ignore comments / whitespace instead of 
having an "_" rules everywhere...

Thanks.

**Comment by Hardmath123** [comment]
If you're using a tokenizer and feeding nearley the resulting tokens, then yes. Otherwise, no, but it's not really that bad—and it forces you to think about where whitespace should be (which is actually kind of important).

**Comment by bd82** [comment]
Thanks.
