### ISSUE TITLE
Proposal: One-size-fits-most postprocessor

### ISSUE THREAD

**Issue by bobbybee** [Hardmath123/nearley#122]
Given that we now have primitives like whitespace and strings defined in the standard library, it may simplify grammar development to have a standard postprocessor with the following characteristics:

* The parse tree is still serialized to an array-of-array style tree.
* The first element of each array is the name of the parsed nonterminal.
* The rest of the array is the parsed nonterminal, except for whitespace.
* Strings are joined together.

Some questions I have:
* What about optional parses?
* Can some preprocessors be overridden for implementing, e.g., standard library functions cleanly?
* (Most important) Is this feature creep?

**Comment by Hardmath123** [comment]
I'm confused about what you're suggesting, which means it's almost certainly feature creep (and, more importantly, too confusing for a user to get started with quickly).

**Comment by bobbybee** [comment]
Given the following grammar and the test string `sin(cos(pi))`:

````
Trigonometry -> _ "sin" _ "(" Trigonometry ")"
              | _ "cos" _ "(" Trigonometry ")"
              | Constant

Constant     -> _ "pi"
              | _ "tau"
````

I would like to get the result:

````
["Trigonometry", "sin", "(", [
    "Trigonometry", "cos", "(", [
       "Constant", "pi"
   ]
]
````

**Comment by Hardmath123** [comment]
Yeah, I don't think this is a worthwhile feature. It'll add a lot of complexity for a feature that is pretty much useless most of the time.
