### ISSUE TITLE
compiler fails when no terminating newline

### ISSUE THREAD

**Issue by uriva** [Hardmath123/nearley#128]
```
root -> "hello"
#
```

> /home/uri/.npm-global/lib/node_modules/nearley/lib/compile.js:22
>     for (var i = 0; i < structure.length; i++) {
>                                  ^
> 
> TypeError: Cannot read property 'length' of undefined
>     at Compile (/home/uri/.npm-global/lib/node_modules/nearley/lib/compile.js:22:34)
>     at StreamWrapper.<anonymous> (/home/uri/.npm-global/lib/node_modules/nearley/bin/nearleyc.js:50:17)
>     at emitNone (events.js:91:20)
>     at StreamWrapper.emit (events.js:185:7)
>     at finishMaybe (_stream_writable.js:488:14)
>     at endWritable (_stream_writable.js:498:3)
>     at StreamWrapper.Writable.end (_stream_writable.js:463:5)
>     at ReadStream.onend (_stream_readable.js:512:10)
>     at ReadStream.g (events.js:286:16)
>     at emitNone (events.js:91:

**Comment by Hardmath123** [comment]
Mmm, that's expected behavior looking at the grammar (I think all lines should be terminated by `\n`).

**Comment by bobbybee** [comment]
Perhaps a more useful error message would be necessary, then?

**Comment by sandiegoscott** [comment]
@Hardmath123 this is a compilation error. If the grammar file ends with the '#' character compilation crashes. Add \n after # and it compiles fine. Not the most important of bugs, admittedly.

**Comment by Hardmath123** [comment]
Yeah, but I'm not sure this is actually an error. I want to enforce "must have `\n` to end comments", and I feel that everyone *should* be ending files with trailing newlines anyway.

**Comment by bobbybee** [comment]
@Hardmath123 Never overestimate casual users :laughing:

**Comment by nanalan** [comment]
I just ran into this error and got totally confused.

> I feel that everyone should be ending files with trailing newlines anyway.

Agree with you, although you still shouldn't rely on that. As a quick fix you could try appending `\n` to the input of `nearleyc`...

**Comment by bobbybee** [comment]
On Sat, Dec 31, 2016 at 03:58:40AM -0800, alex wrote:
> I just ran into this error and got totally confused.
> 
> > I feel that everyone should be ending files with trailing newlines anyway.
> 
> Agree with you, although you still shouldn't rely on that. As a quick fix you could try appending `\n` to the input of `nearleyc`...
In some cases I did that myself:

See https://github.com/bobbybee/uPresent/blob/master/browser/IDE/ide.js#L15 :-)

**Comment by Hardmath123** [comment]
Closing — nobody else complained about this.
