### ISSUE TITLE
parser has state?

### ISSUE THREAD

**Issue by uriva** [Hardmath123/nearley#129]
I ran into some trouble using `feed` iteratively, then saw in the docs that it is meant for reading input in parts.

This means that if you want to parse multiple times you need to create a new parser object every time. Is that as intended?

**Comment by Hardmath123** [comment]
Yes, exactly. You need to instantiate a fresh parser to parse a fresh string.

**Comment by TMiguelT** [comment]
Do you think we should make a nicer API for people who want to parse many separate strings? For example a `.reset()` method that clears state so we don't have to make parser factories every time?

**Comment by tjvr** [comment]
Despite the name, the instantiation of `Parser` is intended to be cheap; you shouldn't worry about creating a fresh one each time. In particular, initialising the first column of the table is something that needs to be done afresh for each parse<sup>*</sup>.

The only avoidable work that's done in the constructor is [this line, making the Rules](https://github.com/Hardmath123/nearley/blob/3b415764680df370317f1de3519bf45263a3b5fa/lib/nearley.js#L215), but that will go away when I refactor `Grammar` into its own thing.

Ideally we'd rename it `Parse`, I suppose, but that seems awkward; and, well, backwards compatibility.

[* @hardmath123: FWIW, I'm slightly lying here. Assuming the grammar doesn't change, you _can_ preserve the first column. But you can do that yourself by `rewind(0)`, if we add a rewind feature.]
