### ISSUE TITLE
parser doesn't initialize on a simple example when running with --strict-mode

### ISSUE THREAD

**Issue by uriva** [Hardmath123/nearley#132]
Grammar file:

> root -> ("not"):? "working"

Error:

> /home/uri/bot/node_modules/nearley/lib/nearley.js:167
>                         copy.data[copy.data.length-1] = r.postprocess([], this.reference);
>                                                                               ^
> 
> TypeError: Cannot read property 'reference' of undefined
>     at /home/uri/bot/node_modules/nearley/lib/nearley.js:167:79
>     at Array.forEach (native)
>     at State.process (/home/uri/bot/node_modules/nearley/lib/nearley.js:145:15)
>     at Parser.advanceTo (/home/uri/bot/node_modules/nearley/lib/nearley.js:232:28)
>     at new Parser (/home/uri/bot/node_modules/nearley/lib/nearley.js:221:10)
>     at Object.<anonymous> (/home/uri/bot/main.js:33:14)
>     at Module._compile (module.js:541:32)
>

**Comment by uriva** [comment]
pr in #133

**Comment by Hardmath123** [comment]
Thanks.
