### ISSUE TITLE
Custom tokens not working?

### ISSUE THREAD

**Issue by sandiegoscott** [Hardmath123/nearley#134]
The Custom Tokens grammar on the main Github page:
```
@{%
var print_tok  = {literal: "print"};
var number_tok = {test: function(x) {return x.constructor === Number; }}
%}

main -> %print_tok %number_tok
```
throws an error when fed
```
print 12
```
or
```
print12
```

And the tokens.ne grammar in the examples behaves the same. Should these work?

**Comment by Hardmath123** [comment]
Uh, I think you're misunderstanding what the tokens feature does. You need a tokenizer to actually make your tokens before you feed them to nearley. The tokens test is passing, so I'm pretty sure nothing is broken.

**Comment by touzoku** [comment]
I would like to reopen this issue. Doesn't work for me either.
test.ne:
```js
@{%
var print_tok  = {literal: "print"};
var number_tok = {test: function(x) {return x.constructor === Number; }}
%}

main -> %print_tok %number_tok
```

Compiling:
```
./node_modules/.bin/nearleyc test.ne -o test.js
```

Produced test.js:
```js
// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }

var print_tok  = {literal: "print"};
var number_tok = {test: function(x) {return x.constructor === Number; }}
var grammar = {
    ParserRules: [
    {"name": "main", "symbols": [print_tok, number_tok]}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
```

Running:
```
$ ./node_modules/.bin/nearley-test test.js -i 'print1' -s main
./node_modules/nearley/lib/nearley.js:275
            throw err;
            ^

Error: nearley: No possible parsings (@0: 'p').
    at Parser.feed (./node_modules/nearley/lib/nearley.js:270:23)
    at Object.<anonymous> (./node_modules/nearley/bin/nearley-test.js:81:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

**Comment by touzoku** [comment]
Ah, sorry, after reading the doc again, I understood what you've meant by the custom token support. The implementation is... strange, I'd say, why would you run regular expressions on top of already tokenized stream? The parser supposed to be able to consume the token stream without additional string-to-symbol operation, IMO. I wonder how hard it would be to implement Marpa::R2::SLIF for this case...

**Comment by Hardmath123** [comment]
No, nearley's job is to parse a stream of tokens. Before the unfortunately-named "tokens" feature, it assumed that those tokens were characters. The "tokens" feature allows you to parse streams of non-characters. However, nearley is still *not* responsible for converting a stream of X into a stream of Y. It would be nice to eventually have a small built-in tokenizer just for fun, but I currently don't have time to implement it.
