### ISSUE TITLE
Limiting length of string generated by nearley-unparse

### ISSUE THREAD

**Issue by shamitp** [Hardmath123/nearley#137]
How can I limit the length of the string generated by nearley-unparse? I'm asking because I have some rules in my grammar that allow certain characters to be repeated infinitely (e.g. [\w]+). I also have some right-recursive rules.

**Comment by shamitp** [comment]
Nevermind; I think Issue #94 already addresses this.

**Comment by Hardmath123** [comment]
Ah, yes, thank you for reminding me. #94 needs to be addressed sooner rather than later. @bobbybee can you take a look? It's a fun algorithm that you would enjoy implementing.
