### ISSUE TITLE
Simple output question

### ISSUE THREAD

**Issue by davelnewton** [Hardmath123/nearley#139]
Given a trivial grammar, e.g.,

```
num -> _ int _        {% function(d) { return { foo: d[1] } } %}
     | _ int _ "foo"  {% function(d) { return { foo: d[1] } } %}

```

running through `nearley-test` with an input of "5 foo" works as expected.

If I run it through with just an `int`, though, the results are empty. I imagine there's a reason for this, or I'm doing something staggeringly wrong, but I'm not sure what it is. Any help is appreciated--thanks!

**Comment by thekarel** [comment]
Try it with `'1'` not just `1` (string vs number).

**Comment by davelnewton** [comment]
@thekarel Hi--this is interesting. The following worked:

    nearley-test -i '"1"' foo-1.js
    
Without the double-quotes it didn't. Is this particularly to how `nearley-test` is grabbing the input? If so, it's a little annoying because I spent quite a while trying to figure out what was happening, but ultimately this is great, because it means stuff was working and I can move forward. I'll set up an environment so I can use it in a more-realistic environment.

Thanks so much!

**Comment by thekarel** [comment]
I think the point is you need to make sure you pass a string to nearley and not a number. In this particular case it's more a shell quirk than anything related to the parser itself.

To double check you can try to run a JS test using a number. For example modify https://github.com/Hardmath123/nearley/blob/master/test/launch.js#L52 to 

```
    it('calculator example', function() {
        var arith = nearleyc("examples/calculator/arithmetic.ne");
        parse(arith, 1)
            .should.deep.equal([ ]);
    });
```

**Comment by davelnewton** [comment]
@thekarel 	Okay, that's what I assumed after your first response--I'll check it out tonight. Thanks again; I thought I was going crazy!
