### ISSUE TITLE
use npm package instead of git for railroad-diagrams

### ISSUE THREAD

**Issue by thejohnbackes** [Hardmath123/nearley#140]
This request is to add railroad-diagrams via the npm package https://www.npmjs.com/package/railroad-diagrams instead of via git. Our internal system does not allow us to compile npm modules with git dependencies.

"No problem," you might say. "It's optional." It's not that easy, though. We are using a package that has Nearley as a dependency two-layers deep. `styled-components -> css-to-react-native -> nearley -> railroad-diagrams`, so we can't simply install without railroad-diagrams.

This isn't to spark an argument about "future-proofing," but a very practical request that will allow us to use a library that depends on Nearley.

What do you think? Might this be possible?

**Comment by thejohnbackes** [comment]
ps. I'm happy to submit the PR myself.

**Comment by Hardmath123** [comment]
Pffffffft I thought #115 dealt with this. That was literally why I merged #115. Does the optionalDependency whatsit not work if it's a dependency of a dependency?

**Comment by thejohnbackes** [comment]
it does, but it's an issue of our dependency management system, which doesn't support git dependencies inside npm repos. 

We have a sort of private npm repository, which makes the library available internally. The npm repo itself doesn't enforce --no-optional. That's up to the developer. So to prevent unintended consequences, all git repos are disallowed as dependencies.

There isn't (as far as I can tell) a way to enforce --no-optional as a package.json configuration.

Like I said, this is a practical, not philosophical request.

is there a reason to use a git repo in this case when it looks like the npm module is just a pointer to the git repo?

**Comment by Hardmath123** [comment]
So, despite me using the feature whose *purpose* is to allow a package to be installed even if certain optional dependencies fail to be installed, the package isn't installing because certain optional dependencies fail to be installed? You know what, I don't even care anymore. 0591eab01c46e90d0cc26e96873d3bef5df47db8.
