### ISSUE TITLE
Exponent "^" has a special behaviour?

### ISSUE THREAD

**Issue by etiennedm** [Hardmath123/nearley#143]
I've spent the last 2 hours trying to figure out why my grammar cannot parse the "^" character. Here is the test I'm currently staring at, trying to figure out what I'm doing wrong.

Grammar: `test -> ("a" "^" "a") | ("b" "@" "b")`

When I try to parse `b@b` I get: `[ [ [ 'b', '@', 'b' ] ] ]`.
BUT when I try `a^a` it fails with `Error: nearley: No possible parsings (@2: '^').`. It also fails with this grammar `test -> ("a^a") | ("b" "@" "b")`.

So what am I doing wrong here?

**Comment by Hardmath123** [comment]
Cannot reproduce:

```
$ nearley-test -q -i "a^a" <(nearleyc <(echo 'test -> ("a^a") | ("b" "@" "b")'))
[ [ [ 'a^a' ] ] ]
```

Make sure you're running the latest nodejs/nearley.

**Comment by bobbybee** [comment]
I can confirm I cannot reproduce this either.

**Comment by etiennedm** [comment]
Ok, so I was testing using windows command line, and it turns out the caret character is used to escape special characters. I still don't know why `nearley-test -q -i "a^a"` does not work (since the string is between quotes), but I won't look further. It works fine when I use the grammar in javascript, and I'll work on my grammar using something else than cmd.exe.

Sorry for the confusion and thanks for trying to reproduce the issue!
