### ISSUE TITLE
sqstring does not properly handle escaping the single quote

### ISSUE THREAD

**Issue by gajus** [Hardmath123/nearley#150]
`'foo\' bar'`

produces an error:

> Error: Unexpected token ' in JSON at position 2

**Comment by Hardmath123** [comment]
Welp, yeah. It's because I thought it was a good idea to piggyback on JSON strings, which don't have `\'` (JSON only has double-quoted strings).

**Comment by gajus** [comment]
I ended up using:

```
dqstring ->
  "\"" dstrchar:* "\"" {% d => d[1].join('') %}

dstrchar ->
    [^"] {% id %}
  | "\\\"" {% d => '"' %}

sqstring ->
  "'" sstrchar:* "'" {% d => d[1].join('') %}

sstrchar ->
    [^'] {% id %}
  | "\\'" {% d => '\'' %}
```

is there any downside to it?

**Comment by Hardmath123** [comment]
This doesn't allow you to have other escapes, right? Like `\n` or `\x1b`.

**Comment by gajus** [comment]
I see.

Thats not a problem in my case, but I can see why you'd want that. Maybe there should be separate inbuilt presets for both options.

**Comment by nanalan** [comment]
With a tokenizer, this'd be pretty easy:

```
\\ = %backslash_escaped
\' = %sq_escaped
' = %sq
```

...due to how precedence works with `tokenizer2` and stuff.
