### ISSUE TITLE
Duplicate results

### ISSUE THREAD

**Issue by facekapow** [Hardmath123/nearley#153]
Hi, I gotta say, this is a mighty nice parser generator!

But, unfortunately, I've run into a bug (whether it's a bug with nearley or my code, I'm not sure).

I get duplicate results when using the following grammar and the following input:
Grammar:
```nearley
# I've eliminated unnecessary parts

#
# Shared Postprocessors
@{% function join($) {
  var res = '';
  for (var i = 0; i < $.length; i++) {
    var curr = $[i];
    if (curr === null) continue;
    var str = String(curr);
    if (Array.isArray(curr)) str = join(curr);
    res += str;
  }
  return res;
} %}
# /Shared Postprocessors
#

#
# Rules (a.k.a. non-terminals)
main ->
    statements NEWLINE:* {% function($) {
      return new MultiScript.Script($[0]);
    } %}

statements ->
    statements NEWLINE:+ statement {% function($) {
      $[0].push($[2]);
      return $[0];
    } %}
  | statement {% function($) {
      var states = new MultiScript.Statements();
      states.push($[0]);
      return states;
    } %}

statement ->
    expression {% function($) {
      return new MultiScript.ExpressionStatement($[0]);
    } %}

expression ->
    FLOAT {% function($) {
      return new MultiScript.FloatExpression($[0]);
    } %}
  | INTEGER {% function($) {
      return new MultiScript.IntegerExpression($[0]);
    } %}
# /Rules
#

#
# Tokens (a.k.a. terminals)
FLOAT -> [0-9]:+ "." [0-9]:+ {% join %}
INTEGER -> [0-9]:+ {% join %}
NEWLINE -> "\n"
# /Tokens
#
```
Input:
```
0.6
```
Result:
```
[ Script {
    expressions: 
     [ ExpressionStatement { expression: IntegerExpression { underlyingValue: '0' } },
       ExpressionStatement { expression: FloatExpression { underlyingValue: '0.6' } } ] } ]
```

Am I doing something wrong, or is it nearley's problem?
Sorry for any trouble, I'm just switching over from Jison.

**Comment by Hardmath123** [comment]
```$[0].push($[2]);```

My guess is that you're having problems because `.push` has side-effects (it mutates the underlying data structure). Try using `Array.concat` instead; does that fix your issue?

**Comment by facekapow** [comment]
Yeah, suprisingly! That's a little gotcha in the parser grammar, isn't it? Thanks for the help!

I'm gonna close this 'cause my problem's fixed, but, just out of curiosity, was it documented somewhere and I overlooked it? Otherwise, it seems like it should be documented since it's strange to someone coming from a different parser where this doesn't happen.

**Comment by Hardmath123** [comment]
No, it's not really documented anywhere. I'm just a functional programmer at heart and I guess I felt "avoid side effects" should be implicit. :-)

By the way, if you send me a PR adding in a sentence to README.md that *you* think would be helpful to someone getting started with nearley, I would happily merge it. It's often hard for project maintainers to write newbie documentation because we overlook the simplest stuff!
