### ISSUE TITLE
Python-style block indentation?

### ISSUE THREAD

**Issue by facekapow** [Hardmath123/nearley#154]
How would one go about doing Python-style whitespace-based indentation?
I know it's possible because CoffeeScript (which uses Jison, and therefore should be easier to do with Nearley) does it, but unfortunately, they don't have their parser source file in the repo, so I can't base anything off that.
I know this is a pretty broad question, but I would appreciate any help 😄 .

**Comment by bd82** [comment]
I think Python style indentation is normally done as part of a separate lexing step.
See an antlr4 Python Grammar:
https://github.com/antlr/grammars-v4/tree/master/python3

CoffeeScript also handles this at the lexer phase:
http://coffeescript.org/v1/annotated-source/lexer.html

I believe that without special handling of those tokens (indent/outdent) at a prior stage
The grammar won't even be context free.

**Comment by Hardmath123** [comment]
Yeah, @bd82 is correct. You should use a lexer to create "INDENT" and "OUTDENT" tokens as part of the token stream.

**Comment by facekapow** [comment]
Ok, let's say I have tokenized my stream and have my own custom ident and outdent tokens, how do I give them to nearley? Through `feed`? If so, do I have to do something like:
```js
parser.feed(['blah:', { token: 'INDENT' }, 'rest of block', { token: 'OUTDENT' }, 'out of the block']);
```

**Comment by bd82** [comment]
That is how it worked for me when implementing a JSON grammar.

[Nearley JSON grammar](https://github.com/SAP/chevrotain/blob/gh-pages/performance/jsonParsers/nearley/json_grammar_tokenizer.ne)
[Hand-Built Lexer](https://github.com/SAP/chevrotain/blob/gh-pages/performance/jsonParsers/nearley/hand_built_lexer.js)
[feeding the token vector to the parser](https://github.com/SAP/chevrotain/blob/gh-pages/performance/jsonParsers/nearley/api.js)

**Comment by facekapow** [comment]
Ok, thanks @bd82!
