### ISSUE TITLE
Document how to reset the parser after using feed

### ISSUE THREAD

**Issue by gajus** [Hardmath123/nearley#156]
```js
const parser = new Parser(commandGrammar.ParserRules, commandGrammar.ParserStart);

const results = parser.feed(command).results;
```

How to reset the parser after feeding it some data?

**Comment by Hardmath123** [comment]
The easiest way is to just make a new parser.

**Comment by gajus** [comment]
Now the most efficient way, though.

It would be nice to have a simple "reset" function.

**Comment by tjvr** [comment]
> Now the most efficient way, though.

It's actually [very cheap](https://github.com/Hardmath123/nearley/issues/129).
