### ISSUE TITLE
Dynamically Scoped Macro Example

### ISSUE THREAD

**Issue by antimatter15** [Hardmath123/nearley#160]
I was trying to run this example from the README

```
foo[X, Y] -> bar["moo" | "oink" | "baa"] $Y
bar[Z]    -> $X " " $Z # 'remembers' $X from its caller
main -> foo["Cows", "."]
```

But running `nearleyc` throws this error

```Error: nearley: No possible parsings (@23: '|').```

For a more minimal failing case:

```test[X] -> $X
hi -> test["merp" | "derp"]```

**Comment by Hardmath123** [comment]
Oh. The stuff inside should be in parens -- `test[("merp" | "derp")]`. Sorry for the misleading documentation — I'll fix that.

**Comment by antimatter15** [comment]
Thanks!
