### ISSUE TITLE
Thoughts on v3 API

### ISSUE THREAD

**Issue by tjvr** [Hardmath123/nearley#169]
@hardmath123 I've been thinking about the relationship between SPPF-style and predicates. Here are some thoughts...

---

Currently, we have postprocessors that have two functions:

- **build** the parse tree
- control the parse by `reject`ing (i.e. act as **predicates**).

If we can delay building the parse tree until the end, this will enable some optimisations (e.g. SPPF-style structure; e.g. not building intermediate parse trees that don't survive to be part of the final result.)

But predicates still need to run during the parse. (Running them at the end, to prune the forest, wouldn't be good enough; we might waste a lot of work on ultimately rejected parses.)

I propose splitting builders and predicates into separate methods, on an object called a "factory". The expression inside the `{% ... %}` in a Nearley grammar is interpreted as a Factory. We can make a Factory from any of the following:

- an instance of Factory, or an object with factory-like attributes
- a callable, which we interpret as a `decode` method
- otherwise we interpret it as a literal, and make corresponding `decode` and `encode` methods.

Examples:

```nearley
@%{

class Block extends Factory {
  constructor(selector, ...argIndexes) { ... }
  decode(...children) { return [this.selector, children[argIndexes[0]] ...
  encode(array) {
    if (array[0] !== this.selector) return false;
    return [null, null, null, null, null, array[1]];
  }
}

%}

Block -> "set" _ "x" _ "to" _ Number {% block('setXPos:', 6) %}

Number -> digits {% a => parseInt(a) %}

m_key -> "left" _ "arrow" {% 'left arrow' %}

```

A Factory has the following attributes:

- `decode`: takes nodes passed as arguments, and returns a new node. _e.g._ `(cow, _, pillow) => { cow, pillow }`.
- `predicate`: returns a boolean: True to allow the parse, False to reject it. It takes two **States** (left, right) as arguments. This should be powerful enough to (a) allow rejecting unwanted strings and (b) write powerful add-ons like feature structures. I need to elaborate on this a bit more though!
- `encode`: takes a node, and returns an Array of nodes suitable for generating a string derivation of this grammar rule. This is part of the "reverse parser" feature I'd like to implement.

**Comment by Hardmath123** [comment]
So, this is backwards-incompatible with respect to predicates, right? (I imagine we can make it backwards-compatible with respect to postprocessors using some sort of hackery.) I feel if we're *going* to be backwards-incompatible anyway, then we can afford to really think about the design and come up with something much easier to use.

The reason I'm iffy about factories is that you now need to make a new class for every single postprocessor, and nearley grammars tend to have a *lot* of postprocessors. I would go the opposite way, and try to minimize the amount of code you need to write to make a postprocessor/reject work.

Also, I don't yet believe that *encode* is necessary: why should a parser care what you do with your AST?

**Comment by tjvr** [comment]
> if we're going to be backwards-incompatible anyway

I didn't think I'd convinced you yet we can get away with this?
I think I'd be favour of going for 80% compatibility? Most old grammars will still work, but maybe edge cases like predicates will break on you.
We'll just have to make really compelling tooling improvements in other areas to convince everyone to do the work to upgrade ;-)

> The reason I'm iffy about factories is that you now need to make a new class for every single postprocessor

That's why I'd like to implicitly create factories from "any of the following", above; most of the time you'd just supply a function, and Nearley would do the Right Thing.

> I don't yet believe that encode is necessary

Because I want a reverse parser! :P This should really have its own issue; but for now, let's just say it will be useful (required?) for auto-complete in `nearley-codemirror`, and it could help your unparser give prettier output. :)

**Comment by Hardmath123** [comment]
> I didn't think I'd convinced you yet we can get away with this?

Semantic versioning. :D

And my (potentially incorrect) belief that nobody actually uses predicates. Again, I'd love empirical evidence one way or another on this. (Some people hotlink nearley.js from GitHub; if they use `reject` then their code would break automagically. :-/)

> That's why I'd like to implicitly create factories from "any of the following"

So every time I write JS that does something like that, a small part of me cries. Currently, symbols in rules could be Strings (which means it's the name of a postprocessor), regexes (recognized by a `.test` method), tokens (also recognized by a `.test` method), or arbitrary things (compared with `===`). That's terrifying!

Let's think harder about this. I bet there's an actually-elegant solution somewhere — it's worth looking for it.

> Because I want a reverse parser!

So, provide `.toString()` methods on each of your tokens in the tokenizer, and simply *don't run postprocessors*. Then reverse-parsing is the same thing as `(fmap toString) . flatten`.

**Comment by tjvr** [comment]
> Some people hotlink nearley.js from GitHub

Right, this is why for scratchblocks I keep different versions hanging around on GitHub Pages. :P https://github.com/scratchblocks/scratchblocks.github.io/tree/master/js semver FTW!

**Comment by tjvr** [comment]
> implicitly create factories

If this upsets you, how about: Factories are always functions; but they may optionally have some extra attributes attached?

**Comment by tjvr** [comment]
Also: it's possible we _could_ implement a backwards-compatibility hack so that old-style predicates continue to work, by evaluating them while building the resulting parse tree. We'd do loads of unnecessary work this way (we'd consider many failing parses), so it'd definitely be slow, but it might(?) be better than a forced grammar upgrade?

**Comment by Hardmath123** [comment]
> Right, this is why for scratchblocks I keep different versions hanging around on GitHub Pages.

Right, but it's too late for that now… :P

> Factories are always functions; but they may optionally have some extra attributes attached?

Hmm, still not convinced. I think we can invent a better interface. Something really intuitive.

> Also: it's possible we could implement a backwards-compatibility hack so that old-style predicates continue to work, by evaluating them while building the resulting parse tree.

We could also provide an option to disable this with newer grammars. `--fast-predicates` or something.

**Comment by Hardmath123** [comment]
I haven't had time to really grok SPPF yet, but here are two questions you might be able to answer for me:
- Does SPPF let you lazily traverse an iterable that yields all possible parses? If so, we could always create this iterable and then run predicates on each one until we find one that matches.
- Would SPPF let you specify a "greedy" mode for a symbol in a rule? For example, `exp -> exp "^" exp!greedy` would force right-associativity.

**Comment by tjvr** [comment]
> Does SPPF let you lazily traverse an iterable that yields all possible parses?

Yeah, you can do this. :) [It's easier to write if you allow generators, but I haven't looked into performance for this yet.]

Regarding greedy mode: I'm not sure. Probably, if you write a derivation chooser that prefers longer right-hand sides. (Come to think of it, we should probably make this entirely pluggable; maybe ask me to explain that one next? :P)

**Comment by tjvr** [comment]
@Hardmath123 I think you're right, and keeping postprocessors as plain functions would be best. Although I still support switching postprocessors to `apply()` :-)

Consolidating this into #186.
