### ISSUE TITLE
Reverse parser

### ISSUE THREAD

**Issue by tjvr** [Hardmath123/nearley#170]
Not to be confused with the unparser (which is already a thing).

[Continuing the discussion about `encode()` from #169...]

@hardmath123 In tosh, currently I have fragile hand-rolled code to output minimal syntax given a Scratch AST JSON. It's buggy and doesn't understand operator precedence properly.

I realise it's an uncommon problem. But it does seem like something that could be derived from the CFG itself, and so therefore something it makes sense to add as part of nearley's tooling—don't you think?

I suspect it may end up to have other benefits/use cases; e.g. in auto-complete in nearley-codemirror, and making the unparser's output prettier (e.g. not producing unnecessary whitespace!)

**Comment by Hardmath123** [comment]
From #169: can't you just map `.toString()` over the flattened, non-postprocessed tree?

**Comment by tjvr** [comment]
That doesn't help me get tosh syntax from Scratch JSON; nor does it help me work out where parentheses are required! :-)

**Comment by Hardmath123** [comment]
Oh. Gotcha.

**Comment by Hardmath123** [comment]
This seems like a thing a parser should not be involved with.

**Comment by tjvr** [comment]
It *is* to do with the CFG.

But now you mention it, maybe you're right; do one thing well, and all that. Clearly I'll have to write a nearley-reverse module :-)

**Comment by Hardmath123** [comment]
> It is to do with the CFG.

So are a lot of things, but that doesn't mean a parsing library should bend over backwards to help support it.

> do one thing well, and all that

Yeah. I think your tosh problem is really too specific to be handled by nearley in general. (Though, I do remember someone else asking this exact same question… maybe @bobbybee? Not sure.)

**Comment by bobbybee** [comment]
> Yeah. I think your tosh problem is really too specific to be handled by nearley in general. (Though, I do remember someone else asking this exact same question… maybe @bobbybee? Not sure.)

Indeed.

Lightly edited IRC logs for reference.

> <alyssa> Are there known algorithms (or proofs against their existence) to map from an AST to a program source given the grammar?
> <alyssa> i.e. go from (+ 1 1) to "1 + 1"
> <alyssa> https://en.wikipedia.org/wiki/Unparser is not particularly helpful...
> <hardmath123> It depends on how the program source is turned into the AST.
> <hardmath123> But I'll give you a hint: there exist these things called "javascript beautifiers" and "javascript minifiers".
> <alyssa>  Wait, isn't this just fancy pattern matching if you restrict it enough?
> <hardmath123> And there's this thing called "Haskell" that can derive show and read instances of adts.

**Comment by Hardmath123** [comment]
> nor does it help me work out where parentheses are required!

(Thinking about it, this is kind of a fascinating problem on its own… 🌵)

**Comment by wizzard0** [comment]
I did that at some point for PEG, but in general this task is not easy at all.

It is kinda doable when you don't do any postprocessing in callbacks, or use predicates, but when you do - it becomes undecidable.

Also, not every AST corresponds to an AST which may be produced by a given grammar... but that's a different can of worms.

**Comment by tjvr** [comment]
I'll do this as a separate project. :-)

**Comment by tjvr** [comment]
Prototype complete:
https://github.com/tjvr/nearley-reverse

**Comment by vrockai** [comment]
hey, i get here through the "auto-complete" keyword. wondering whether nearley-reverse could be used for... auto-complete. Like with the main "colors" example from nearley, when I type:
`#FF` I want to get a list of tokens to append to this so that sentence is valid... thus something like `[0-9a-f]`. is it possible?

**Comment by kach** [comment]
This is a question for @tjvr

**Comment by tjvr** [comment]
@vrockai Hey, I'm afraid there isn't any code for automatically doing autocomplete based off a Nearley grammar (yet!). :-)
