### ISSUE TITLE
JS version

### ISSUE THREAD

**Issue by tjvr** [Hardmath123/nearley#177]
@Hardmath123 

* Can we use ES6, or will that make you sad?
* Can we require `Map`? (This allows the use of e.g. `Symbol`s as rule names, and generally prettier internals.)

---

Relevant: <https://kangax.github.io/compat-table/es6/#test-Map>

**Comment by Hardmath123** [comment]
> Can we use ES6, or will that make you sad?

That will make me sad.

> Can we require Map?

Nah, string-keys are fine. What we *really* want here is an ADT that tells us whether we're looking at a rule name, a literal, a token, etc. and the current JSON-ey way suffices until we figure something better out.

**Comment by wizzard0** [comment]
As much as I like ES6 improvements like weakmaps, and like TypeScript, but I must admit sticking with ES5 is important because having a transpiling step when you have to support downlevel JS really really slows down iterations.

**Comment by bd82** [comment]
> having a transpiling step when you have to support downlevel JS really really slows down iterations.

How fast are your iterations and how big is your project?
a 13-14k LOC (Neto) TypeScript project compiles in 3.5-4 seconds for me on the first time (clean).
and **just 1.3-1.5** seconds when performing incremental compilation (-watch/-w mode and editing a single line).

Granted this is a on an I7 MacBook pro, but I think it is just a 4th gen I7 (7th gen out now?)

**Comment by tjvr** [comment]
This is not, in fact, the place to discuss the merits of ES6 vs ES5. If Kartik doesn't want to upgrade, that's good enough for me.
