### ISSUE TITLE
Make GC thing optional

### ISSUE THREAD

**Issue by Hardmath123** [Hardmath123/nearley#183]
It should be disabled when doing nearley-test, or (eventually) when rewinding.

**Comment by tjvr** [comment]
When `rewindable` is enabled, that is. Hmm; should these be options given to parser?

**Comment by Hardmath123** [comment]
Yeah, you should have to specify options when constructing a `new Parser()`. That way nearley-test can do the right thing.

**Comment by tjvr** [comment]
Any suggestion for what this should be called?

**Comment by wizzard0** [comment]
something like `preserveState` maybe...

**Comment by tjvr** [comment]
This is now merged. :)
