### ISSUE TITLE
nearleyc errors

### ISSUE THREAD

**Issue by Hardmath123** [Hardmath123/nearley#188]
If nearleyc throws a parse error when parsing an input `.ne` file, it should print out the line/col where the error happened. The current error message is confusing and messy; it's also useless when trying to locate the error in an editor.

**Comment by tjvr** [comment]
Should the default error be "no possible parsings" or "invalid syntax" or "unexpected token" or something else entirely?

**Comment by tjvr** [comment]
(n.b. the lexer spits out "invalid syntax" if it sees some characters it can't turn into a token, so ideally the parser error would be something different)

**Comment by Hardmath123** [comment]
I'll leave lexer errors to you, but for the parser something like "Invalid syntax" should be fine. We expect people to catch this error and do something meaningful, anyway.

**Comment by Hardmath123** [comment]
Also, to clarify, this issue was meant specifically for nearleyc parsing input `.ne` files. Of course, a general solution would be better, but `.ne` files are a priority because it's easier to debug syntax errors if you, y'know, _know where they are_. :P

**Comment by tjvr** [comment]
> this issue was meant specifically for nearleyc parsing input .ne files

I realise; but the easiest thing is to handle this in a general way, as part of #220. :-)

**Comment by tjvr** [comment]
(If you want to clean up the output, so `nearleyc` users don't see a traceback as well, that's up to you.)

**Comment by Hardmath123** [comment]
> Error: invalid syntax at line 5 col 19: 
> y ->    foo %lasdf.asdf

:D

**Comment by wizzard0** [comment]
Please keep the offset / token index too ;)
