### ISSUE TITLE
Exploring multiple parses with postprocessors

### ISSUE THREAD

**Issue by antimatter15** [Hardmath123/nearley#189]
I'm trying to parse some text even if that text includes some typos. I'm using a postprocessor which computes the levenshtein distance between the current text and some list of tokens, and returns `Parser.fail` unless it's close enough to be recognizable. That is, for any given substring I can continue with 0 or 1 possible parses. 

With a word list consisting of "Cactus" and "Circus", and I enter "Camrus" which happens to be similar to both tokens. I want my postprocessor to emit both "Cactus" and "Circus" as possible ambiguous parses. That is, I want to be able to continue with 2 or more possible parses.

Perhaps instead of returning either a result or `Parser.fail`, there could be a mode where a postprocessor is expected to return a list for possible parses, where an empty list `[]` is equivalent to a rejection, a list of one element continuing along one path, and a list of multiple elements introducing ambiguity as expected.

**Comment by tjvr** [comment]
I think you want a custom tokenizer. You can write a `test()` method on your Token class that does what you want.

**Comment by Hardmath123** [comment]
I think @antimatter15 wants to be able to parse "Camrus Camrus" as the ambiguous parsing `[[Cactus, Cactus], [Cactus, Circus], [Circus, Cactus], [Circus, Circus]]`.

I agree with Tim here. You can make this work by using tokens with custom `.test()` methods that return true only if the Levenshtein distance between the target word and the input is less than N (or something like that). The relevant README section is https://github.com/Hardmath123/nearley#custom-tokens

**Comment by antimatter15** [comment]
Ok, thanks!
