### ISSUE TITLE
Is there an EOF token?

### ISSUE THREAD

**Issue by vihanb** [Hardmath123/nearley#194]
I've started using nearly for my project, and it's going well so far, however the lack of an EOF token is a problem. It looks like this was touched upon in #96, but it was quickly closed without much response.

I'd like to do something like:

```
rule -> a $
      | b
```

where `$` is an EOF token. I'm not sure if I can implement this using test tokens, but EOF might be worth its own token.

**Comment by Hardmath123** [comment]
I don't think we necessarily need an EOF token in nearley. Since nearley parses input incrementally, you can always look at parser.results once you are done feeding input. Maybe it would help if you gave a specific example where you're having trouble?

**Comment by tjvr** [comment]
As hinted at in #96, an EOF token doesn't make much sense.

You'll have to restructure your grammar to avoid this, I'm afraid! :)

**Comment by markusmoenig** [comment]
When I look at this code I get an error when the comment "#" is on the last line as I cannot check if the EOF condition is met. How can I prevent this ?

# Comment
Comment -> "#" _Comment "\n"
_Comment -> null
    | _Comment [^\n]

**Comment by tjvr** [comment]
Either

* rewrite your grammar so that Comment can be at the end
* use separate lexing/tokenization stage (recommended) before parsing with nearley, which can handle newlines & comments etc; or
* add an extra newline to the end of your input, before parsing (bit of a hack but works!) :-)
