### ISSUE TITLE
SystemJS fails to correctly detect module type

### ISSUE THREAD

**Issue by quigleyj97** [Hardmath123/nearley#196]
SystemJS fails to detect the type of the `nearley` module, assuming that it's AMD. It then tries to run it (incorrectly) as AMD, causing module loading to fail.

This is because of #184: Instead of removing the old AMD header in `lib/nearley.js` it simply comments it out. SystemJS detects module type with a regex- it isn't smart enough to ignore comments and as such, due to the [module detection order](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection), it gets incorrectly recognized as AMD.

I confirmed this by removing that commented out code, and `nearley` was successfully detected as CommonJS.

In SystemJS this can be mitigated with explicitly defining the module type in the `meta` config, but we'd prefer if the automatic detection was working because using meta is a bit of a hack.

**Comment by tjvr** [comment]
Ah, sorry about that! Sounds like SystemJS is being a bit silly :P

Care to submit a PR to fix this? We'd be happy to merge it. :)

**Comment by quigleyj97** [comment]
Alright! Submitted the PR
