### ISSUE TITLE
Global Postprocess JavaScript called only once

### ISSUE THREAD

**Issue by markusmoenig** [Hardmath123/nearley#200]
I am working on a shader language and at the start of my post processor code I clear the defined variables:

@{%
    let definedVars=[];
...

However it seems the global code is only called once, at the first invocation of nearly(), which means that definedVars contains the content of the last runs for each new parser pass.

How can I clear the global vars ?

Thanks

**Comment by tjvr** [comment]
If you're trying to mess with global vars from inside nearley preprocessor rules, you're going to have a bad time.

I would split your compiler into stages: use nearley just to do the parsing and built up an abstract syntax tree, and then walk the tree to build your global variables. :-)

**Comment by markusmoenig** [comment]
Yes, this is exactly what I am doing. But I need to initialize the syntax tree and I do that inside the @{% ... %} block. 

However that code is only called once, meaning that the next calls to the nearley parser work on the filled out syntax tree from the last pass (which I dont want).

Any way to call the @{} code every time I initiate a new nearley instance ?

Thanks.

**Comment by tjvr** [comment]
> But I need to initialize the syntax tree

Why would you need to do that? Sounds like a code smell to me. :-)

Anyway: no, no way to do this.

**Comment by Hardmath123** [comment]
(Note: if I understand you right, you can put your "AST initialization" code in the postprocessor for your start symbol to solve your problem.)

**Comment by markusmoenig** [comment]
All I try to do is to catch situations like this:

`float4 f4 = float4( 0, 0, 0, 1 );
float f = 1;

f = f4; # wrong type
`

Todo that I have a definedVars array which holds all user defined variables and their types and I clear it at the beginning of the post processor:

@{%
let definedVars=[];
...

But the problem is this code is run only once, meaning I can never clear definedVars for the next pass. 

I could make this array truly global, like window.definedVars and clear it from the outside, but thought I would ask if there is a less hacky approach first.

Thanks.

**Comment by Hardmath123** [comment]
Ah, I see. I think the correct answer here is that typechecking should happen in a _separate_ pass through the AST — not while you're parsing.

**Comment by markusmoenig** [comment]
Ok, got it, thanks for the answer. However that would increase the complexity of it all by a magnitude and its all working fine right now. So I will hack it for now (and do it right sometime in the future).

**Comment by NodeGuy** [comment]
I'm having this problem too.  I'm trying to de-duplicate variable declarations.  When a new variable is parsed, I check it against a map to see if it's been parsed before:

```JavaScript
@{%
const variables = new Map();
%}

variable -> "$" character:+ {%
  ([, characters]) => {
    const name = characters.join(``);

    if (!variables.has(name)) {
      variables.set(name, {type: `variable`, name});
    }

    return variables.get(name);
  }
%}
```

It breaks if I run the parser more than once because the variables from the previous run are memoized.

**Comment by kasbah** [comment]
>I don't see how I can use the above workaround (window.definedVars) because I'm running on Node.js

You should be able to use `global.definedVars`.

**Comment by tjvr** [comment]
> When a new variable is parsed, I check it against a map to see if it's been parsed before

I would urge you to do this by walking over your parse tree after parsing has finished, not inside your parser. :)

**Comment by NodeGuy** [comment]
@kasbah Thanks, that won't work in Node.js because each module has its own global namespace.

@tjvr That feels inefficient but OK.
