### ISSUE TITLE
JSHint Errors

### ISSUE THREAD

**Issue by markusmoenig** [Hardmath123/nearley#204]
In my company we have the rule to check every JS file with JSHint when compiling the project, as it's a fast and easy way to catch syntax errors and bugs.

Nearley.js throws a few errors, it's easy to rectify them but would be great if these could be fixed in the official repo ?

---

../raysl/nearley.js, line 26 char 26: Misleading line break before '?'; readers may interpret this as an expression boundary. ( '           )'
../raysl/nearley.js, line 28 char 30: Misleading line break before '+'; readers may interpret this as an expression boundary. ( '           )'
../raysl/nearley.js, line 29 char 30: Misleading line break before '+'; readers may interpret this as an expression boundary. ( '           )'
../raysl/nearley.js, line 31 char 2: Missing semicolon. ( '} )'
../raysl/nearley.js, line 114 char 17: 'exp' is already defined. ( '           )'
../raysl/nearley.js, line 126 char 30: 'i' is already defined. ( '           )'
../raysl/nearley.js, line 137 char 2: Missing semicolon. ( '} )'
../raysl/nearley.js, line 148 char 2: Missing semicolon. ( '} )'
../raysl/nearley.js, line 156 char 2: Missing semicolon. ( '} )'
../raysl/nearley.js, line 177 char 9: 'rules' is already defined. ( '    var ru )'
../raysl/nearley.js, line 179 char 2: Missing semicolon. ( '} )'
../raysl/nearley.js, line 185 char 13: 'options' is already defined. ( '        va )'
../raysl/nearley.js, line 187 char 13: 'grammar' is already defined. ( '        va )'
../raysl/nearley.js, line 189 char 20: 'grammar' used out of scope. ( '    this.g )'
../raysl/nearley.js, line 202 char 29: 'grammar' used out of scope. ( '    var co )'
../raysl/nearley.js, line 206 char 18: 'grammar' used out of scope. ( '    column )'
../raysl/nearley.js, line 207 char 20: 'grammar' used out of scope. ( '    column )'
../raysl/nearley.js, line 262 char 21: Misleading line break before '+'; readers may interpret this as an expression boundary. ( '           )'
../raysl/nearley.js, line 280 char 72: Missing semicolon. ( '        th )'
../raysl/nearley.js, line 284 char 50: Missing semicolon. ( '        th )'
../raysl/nearley.js, line 302 char 51: Missing semicolon. ( '    var co )'
../raysl/nearley.js, line 305 char 17: Misleading line break before '&&'; readers may interpret this as an expression boundary. ( '           )'
../raysl/nearley.js, line 306 char 17: Misleading line break before '&&'; readers may interpret this as an expression boundary. ( '           )'
../raysl/nearley.js, line 307 char 17: Misleading line break before '&&'; readers may interpret this as an expression boundary. ( '           )'

---

Thanks.

**Comment by tjvr** [comment]
Sorry, we have our own style; we're not going to change it to match JSHint.

**Comment by markusmoenig** [comment]
Ok, thanks for the feedback, will fix them locally.
