### ISSUE TITLE
One-item sequences should not resolve to array

### ISSUE THREAD

**Issue by julien-f** [Hardmath123/nearley#207]
I think it would simplify a lot grammars if sequences with a single element would be unboxed automatically.

```
expression -> boolean | null
boolean -> "true" | "false"
null -> "null"
```

Matching for "true" currently returns `[ [ "true" ] ]`, with unboxing, it would simply return `"true"`.

Currently, to achieve the same result, I have to use a lot of `id`s (especially combined with alternatives):

```
expression -> boolean {% id %} | null {% id %}
boolean -> "true" {% id %} | "false" {% id %}
null -> "null" {% id %}
```

**Comment by tjvr** [comment]
It might be nice, but consistency is important. Anyway, we're not going to change this since it would break compatibility with existing grammars :-)

**Comment by julien-f** [comment]
I don't think it really impacts consistency: a single item is not seen as a sequence for users.

But I understand the compatibility issue, I though about it, but I think this change would really improve the usability of nearley, maybe it could ship in the next major version?

**Comment by Hardmath123** [comment]
> I don't think it really impacts consistency

Yes, it does. A one-item sequence is exactly that: a one-item sequence. `[a]` and `a` are not the same thing, and it would be inconsistent for nearley to behave otherwise.

> a single item is not seen as a sequence by users

…which is why you can use `{% id %}` to unbox it explicitly where needed! :-)

**Comment by julien-f** [comment]
Of course, `[a]` and `a` are different, but in Nearley there is no way to say a single item, everything is a sequence which I find a bit cumbersome to use.

IMHO, I think it's a trade of between purity and usability, but I made my point now it's your call and I respect it 😃

**Comment by tjvr** [comment]
> I made my point now it's your call and I respect it :smiley:

Thanks for your understanding!

One final thought: using `id` is usually less common in practice, since for example
```
boolean -> "true" {% id %} | "false" {% id %}
```
isn't something you'd often write; you want some AST node that represents the value (e.g. `() => true`), not usually the string value `"true"`! :-)

**Comment by julien-f** [comment]
That's true, but I find myself doing a double-extraction with alternatives:

```
literal -> (number | record | sequence | string) {% d => d[0][0] %}
```

**Comment by heyitsmeuralex** [comment]
I often find myself doing something similar to the following:

```ne
Literal  -> StringLiteral {% d => d[0] %}
         | IntLiteral    {% d => d[0] %}

StringLiteral -> dqstring            {% d => [ 'StringLiteral', d[0] ] %}
               | sqstring            {% d => [ 'StringLiteral', d[0] ] %}

IntLiteral    -> [0-9]:+             {% d => [ 'IntLiteral', d[0].join('') ] %}
```

i.e. naming things and grouping them together with `id` (`d => d[0]` is equivalent) calls.

**Comment by deltaidea** [comment]
Here's a common use case that requires one-item arrays to be as they are now:
```
declarationStatement -> declaration | declaration initialValue
```
If the first alternative is unboxed, I can't check `.length` later to see if it's 1 or 2.

Another edge case:
```
statement -> expression:+
```

What if there's only one expression there? Should I expect it to be in an array or not?

I know it's sometimes annoying to do `d[0][0][0]` but it's a trade-off for consistency. Imagine `d[0][0][0]` is suddenly unboxed into `d`. Now you'd have to do a lot more of `undefined` checks for alternatives.

**Comment by julien-f** [comment]
@deltaidea IMHO, your first example would be better as `declarationStatement -> declaration initialValue:?`.

And in the second case, it would obviously always be an array (same with `:*`).

**Comment by deltaidea** [comment]
Yes, it looks cleaner the way you wrote it, but the the original is still allowed. You wouldn't just ban the edge cases. They will also be subjective as people will find different things confusing.
What about `statement -> foo | bar qux`? Is `foo` an array or not? If yes, you're saying the same rule should have different results depending on alternatives.
Personally, I find it easier to work with current consistent model. It doesn't force me to think as much, and I can focus on higher-level stuff.

P.S. In ES6+ use parameter destructuring: `([ part ]) => { type: 'Statement', value: part }`
