### ISSUE TITLE
Use "?", "+", "*" as syntaxes

### ISSUE THREAD

**Issue by grandsong** [Hardmath123/nearley#213]
# Motivation

There are two groups of usages of "?" (as well as "+" and "\*"), *neither* of which is simple and intuitive.

## Usage 1: In names of rules

For example, in "lib/nearley-language-bootstrapped.ne", there are many (21, to be precise) `whit?`s.
(Note: The total rules are just 26.)

Its rule is:

	# Optional whitespace with a comment
	whit? -> null
		| whit

Similarly, there is `whitraw?`

	# A string of whitespace OR the empty string
	whitraw? -> null
		| whitraw

It looks weird that names includes operator-like characters which actually indicate operations.

And it seems to be a major cause of the flawed design as follows...

## Usage 2: After ":"

`:?` and `:+` appear in "builtin/number.ne".

	int -> ("-"|"+"):? [0-9]:+ {%
		function(d) {
			if (d[0]) {
				return parseInt(d[0][0]+d[1].join(""));
			} else {
				return parseInt(d[1].join(""));
			}
		}
	%}

The rules there heavily resemble RegExp. But the ":"s make the expressions bizzare.

":" is a typical *separator*, and thus alienates the operators (`?` and `+`) from their operands.

# Proposed Solution

- Remove ":", so that quantifiers "?", "+", "*" can work alone as they do in RegExp.
- Disallow operator-like characters in names.

Things will be much neater.

# Illustrative Examples

So, 

	batman -> "na":* "batman" # nananana...nanabatman

will be simply...

	batman -> "na"* "batman" # nananana...nanabatman

In "lib/nearley-language-bootstrapped.ne", the rules of `whit?` and `whitraw?` will be removed.

Still, the rule...

	whit -> whitraw
		| whitraw? comment whit?

will remain unchanged, but "?"s here are operators. The production will be treated (implicitly) as...

	whit -> whitraw
		| (null | whitraw) comment (null | whit)

# Impacts?

Productions like `whit?` will be removed, of course.

I doubt anyone will miss them, though.

# Derived Proposal

A misuse of "+" in names may be related with this topic, so I write it here.

## Use "?" for self recursions

In "lib/nearley-language-bootstrapped.ne", there is...

	expression+ -> completeexpression
		| expression+ whit? "|" whit? completeexpression  {% function(d) { return d[0].concat([d[4]]); } %}

"+" in the name indicates the production repeats itself, *somehow*.

However, immediately below you see...

	expressionlist -> completeexpression
		| expressionlist whit? "," whit? completeexpression {% function(d) { return d[0].concat([d[4]]); } %}

The *real* differences between the two are just "|" vs ",".

Here comes a question: If "+" could apply to the former, why not the latter?

I think "expression+" should be named "expression_union".

"+" here is unnecessary. In fact it shouldn't appear at all because recursion is not the correct usage of this operator character.

With "?" as syntax, now we can write...

	expression_union -> ( expression_union whit? "|" whit? )? complete_expression  {% function(d) { return d[1].concat([d[5]]); } %}

	expression_list -> ( expression_list whit? "," whit? )? complete_expression  {% function(d) { return d[1].concat([d[5]]); } %}

Note that the two corresponding indexes (0 and 4) of `d` are increased by 1 (now 1 and 5) since a pair of `()` is added. This conforms to matches of RegExp in JavaScript.

"+" as operator should be used only for simple repetitions, not for self recursions.

**Comment by Hardmath123** [comment]
The bootstrapped nearley language was written before we had nice EBNF modifiers, so the nonterminals were named to reflect their meaning. I guess in theory we could go through and rename the nonterminals in the file, but it's not user-facing so it's not really a priority.

As for changing the .ne syntax by removing `:`, that would be backwards-incompatible, so I'm hesitant to do that. Also, I like the way the colons look; plain `+?*` would look too raw for my taste.

**Comment by tjvr** [comment]
I'm not sure how I feel about the colons. But it's just syntax, so it's not super-important. :-)

If you want to tidy up the Nearley grammar, and send a pull request, I think that would be good. As long as it still accepts the same language!

**Comment by grandsong** [comment]
> that would be backwards-incompatible, so I'm hesitant to do that.

Backwards-compatible is indeed important.

And that's exactly why I suggest you rethink early. 

If, and we wish, Nearley grows popular and more and more people use it, they will complain while the syntaxes become more and more difficult to change even a tiny bit.

> it's not user-facing so it's not really a priority.

I use bootstrapped.ne as *a mere example* but the issue is *not* about whether user-facing or not.

The problem is: "some?" is a name with an operator-like character, while "some:?" is "some" with a quantifier operator.

Two usages for similar (or same) purposes. That is confusing and non-inituitive.

Nearley syntaxes are generally good. It is quite friendly to people familiar with RegExp. But this issue is a downfall.

Nearley is originally for eduction. If you were a student, won't you have mixed feelings about such syntaxes both (naturally) like and (strangely) unlike RegExp?

> plain +?* would look too raw for my taste.

Can you explain what's wrong with them for your "taste"?

What's rationale in this?

> it's just syntax, so it's not super-important.

That's what I had forseen but wished it not happen... Sadly, it does.

I wasn't saying this issue is "super-important". Nothing is "super-important". We can even live quite well without Nearley at all.

I don't know what more important issues you are busy with. This issue may have low priority. That'll be all right. It can be postponed, no matter how long. The jobs will take your time, not mine, so you have all the rights to schedule.

But what I sense here is haste to close the issue by largely neglection. This is a different story.

Syntaxes can insignificant if you are making a mere toy and thus don't expect it be used by many people.

In this case, the *official, default, meta* syntaxes are obviously not a toy. Any decison in its design has profound influence.

Yes, lib users can make their own syntaxes to replace the official one of Nearley. But it doesn't mean the official one will be used less and flaws in it can be happily ignored.

Don't tell me you look forward to students creating their own bootstrapped.ne for a learning-in-doing purpose.

I already forked Nearley and of course I can make my own modified bootstrapped.ne.

However, I presume you understand your lib very well and I'd like to discuss with you to learn what you think and reason about this issue.

**Comment by grandsong** [comment]
If you allow something bad in your grammar (actually, any kind of rules), it would cause abuse or at least confusion.

You allow "?" and "+" in names of productions. And worse, you set bad examples in your official bootstrapped.ne (due to early decisions which is understandable but people won't know).

People will readily do so.

Or, when they don't, they will wonder if they are making right decisions since you officially have given them opposite implications.

I bet most lib users will read bootstrapped.ne for both understanding what's going on when parsing other .ne files and learning how to write a .ne file. I also suspect you will encourage your students to do so.

That's why I don't agree this issue is negligible.

---

I plan to use Nearley for my language which has many in common with CoffeeScript, Python, Lua, etc.

And I guess a propotion of lib users are like me.

I am looking for grammar for syntaxes as neat as possible.

A good, or even ideal, example is the grammar of [TypeScript grammar](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a-grammar).

You can see `opt` in a small font appears many times which serve as `?`. Except that, no complex things. Very neat and elegant.

Nearley doesn't need to be that neat. Still, I hope it can move closer to that.

**Comment by tjvr** [comment]
Sorry; as we've already explained, we can't change the syntax for backwards compatibility reasons. Lots of people are already using Nearley in the wild.

We agree that the bootstrapped grammar could use some tidying up. Hopefully we'll get round to that soon. :-)
