### ISSUE TITLE
Npm Package Naming Collision?

### ISSUE THREAD

**Issue by mysterycommand** [Hardmath123/nearley#216]
Hey, I'm trying to install `nearly` with `yarn add nearly` but it looks like the npm registry is pointing at something sortof maybe called `nearly-react`: https://www.npmjs.com/package/nearly, https://github.com/luojunbin/nearly … guess I'll just install from GitHub URL, but thought I'd bring it to your attention.

**Comment by Hardmath123** [comment]
It's nearl_e_y, with an E between the L and the Y. :-)

**Comment by mysterycommand** [comment]
Aaaaahhhh yeah, #dontdrinkandcode
