### ISSUE TITLE
Is it normal with so many calls?

### ISSUE THREAD

**Issue by grandsong** [Hardmath123/nearley#217]
When I tinkered with the bootstrapped.ne in my fork, I add `console.log(d[0]);` before `return ...` to the js function in the rule of "prod", so that I could see how "prod" rules are executed.

To my big surprise, there are way too many calls.

For example, the root "Chunk" occurs 12 times in when parsing the "lua.ne" among examples.

I alos tried this short piece of "ne":

	Chunk -> _ Block _
	Block -> "block" | "block" Block
	_ -> null | _ [\s] {% function() {} %}

I got 12 "Chunk", 8 "Block" and 7 "_".

Is this normal?

**Comment by tjvr** [comment]
Yes.
