### ISSUE TITLE
Allow save/restore of parser state

### ISSUE THREAD

**Issue by tjvr** [Hardmath123/nearley#221]
So I'm convinced that `rewind()` from #165 was the wrong solution.

We should add instead a save/restore API, which the following advantages:

* Does not require `keepHistory`
* Allows you to manage memory usage yourself
* Integrates much better with the Lexer interface

The idea is that e.g. `nearley-codemirror` will be able to save() the parser state at the end of each line. CodeMirror gives you a line at a time for syntax highlighting, and will go back to the first changed line after editing. So we can resume parsing at that point. :-)

**Comment by tjvr** [comment]
@hardmath123 I removed rewind() in 8c33475. It made it into 2.8.0 and 2.7.15. If we do another release since then it will violate semver; either we assume no-one's using `rewind()`, or we re-implement it in terms of save/restore before we do another release. :-)

**Comment by Hardmath123** [comment]
Sounds good to me. I don't think anyone uses `rewind()` yet, so a minor release should be fine.
