### ISSUE TITLE
error handling example

### ISSUE THREAD

**Issue by wizzard0** [Hardmath123/nearley#222]
I heard a lot that there is a lot of parse information available :)

But it would be great to know how to actually extract information like:
`when parsing rule Program > Statement > [AssignmentStatement, FunctionStatement] > ... next token is OpenBracket which is not one of [Expression, Literal, FunctionCall]`

Similar information would be good for developing autocomplete engine I guess.

**Comment by Hardmath123** [comment]
A lot of this has been taken care of in the recent doc overhaul. I'm going to close this issue for now; if you need more help, let us know.

**Comment by Hardmath123** [comment]
(https://nearley.js.org/docs/parser#accessing-the-parse-table)
