### ISSUE TITLE
Result divergence from playground

### ISSUE THREAD

**Issue by freddi301** [Hardmath123/nearley#224]
Hi,
Finally i got the combination that parses words separated by space left-associatively and right-associatively with colons.
But when i use it with nearleyc and nearley-make the parsed results are always right associative

```
@builtin "whitespace.ne"

@{%
  class Atom {
    constructor(name) { this.name = name; }
    toJSON(){ return this.name; }
  }
  class Juxt {
    constructor(left, right) { this.left = left; this.right = right; }
    toJSON(){ return [this.left.toJSON(), this.right.toJSON()]; }
  }
%}

MAIN -> _ TUPLE _ {% d => d[1] %}

TUPLE -> "(" _ PAIR_RIGHT _ ")" {% d => d[2] %}

PAIR_RIGHT ->
  PAIR_LEFT _ "," _ PAIR_RIGHT {% d => new Juxt(d[0], d[4]) %}
| PAIR_LEFT {% d => d[0] %}

PAIR_LEFT ->
  PAIR_LEFT __ PAIR_LEFT {% d => new Juxt(d[0], d[2]) %}
| TUPLE {% d => d[0] %}
| ATOM {% d => d[0] %}

ATOM -> [^\s()\n,]:+ {% d => new Atom(d[0].join('')) %}
```

some tests that in playground parses as i want
```
(a b c)
(a, b, b)
(a b, c d, e f)
```

**Comment by freddi301** [comment]
Just discovered that nearley 2.8.0 gives ambigous parsing where playground not.
Anyway, whats the best way to achieve:

`(a b c)` -> `[['a', 'b'], 'c']`

`(a, b, b)` -> `['a', ['b', 'c']]`

`(a (b c))` -> `['a', ['b', 'c']]`

`((a b) c)` -> `[['a', 'b'], 'c']`

`(a, b c, d e)` -> `[['a', ['b', 'c']],['d', 'e']]`

**Comment by tjvr** [comment]
> Just discovered that nearley 2.8.0 gives ambigous parsing where playground not.

Oops! Looks like #171 must have subtly changed the parse behaviour. But the newer version of nearley (2.8) is actually doing the right thing here: your first grammar has an ambiguity around this point:

```
PAIR_LEFT ->
  PAIR_LEFT __ PAIR_LEFT {% d => new Juxt(d[0], d[2]) %}
```

Your second grammar appears to resolve this ambiguity. As for your question, I'm not sure what you're asking? :-)

**Comment by freddi301** [comment]
You answered the question :)
It was "is the grammar ambigous or It is a bug/divergenze?"
