### ISSUE TITLE
Parsing Whitespace on 2.8.0

### ISSUE THREAD

**Issue by jfosnight** [Hardmath123/nearley#225]
I just installed nearley today and am running 2.8.0.

I have been trying to get a very simple grammar to produce the expected output for the last 45 minutes.  I finally thought I'd try my grammar in the web [playground](https://omrelli.ug/nearley-playground/), and it works fine.

Here is my grammar:
```
lease -> "lease" _ ip
ip    -> int "." int "." int "." int {% function(d){ return [d[0], d[2], d[4], d[6]];} %}
int -> [0-9]:+ {% function(d){return parseInt(d[0].join("")); } %}
_ -> " ":* {% function(){ return null;} %}
```

When I compile and test it using `nearley-test parser.js -i lease10.10.1.0` it produces the expected output: `Parse Results: [ [ 'lease', null, [ 10, 10, 1, 0 ] ] ]`.  However, if I run the same test, but add a space between the lease and 10 (`nearley-test parser.js -i lease 10.10.1.0`) it produces: `Parse Results: []`

Running the same tests in the web playground produces the same results with our without the space (or any number of spaces) as to be expected.

![image](https://cloud.githubusercontent.com/assets/3527971/25406551/ac8011c4-29cc-11e7-9c1a-4c000083d8da.png)

While troubleshooting I reduced my grammar to simply:
```
lease -> "lease" _ "x"
_ -> " ":* {% function(){ return null;} %}
```
and it experiences the same difficulty where it would produce results if I did not include a space, but would not produce a result if I put a space between lease and x.

I have also attached the full output from the two test cases.
[test-space.txt](https://github.com/Hardmath123/nearley/files/956485/test-space.txt)
[test-no-space.txt](https://github.com/Hardmath123/nearley/files/956484/test-no-space.txt)

**Comment by tjvr** [comment]
Hi! Thanks for the detailed bug report :-)

I can't reproduce this, on either master or 2.8.0, for either of your grammars. On closer inspection I can see why...

> `nearley-test parser.js -i lease 10.10.1.0`

You'll need to put "lease 10.10.1.0" in quotes for your shell to treat it as a single argument. All `nearley-test` is seeing is `lease`, plus an extraneous argument which it ignores; and so you get no results! :-)

**Comment by jfosnight** [comment]
Yep, my bad.  I didn't think about needing to use quotes.

Thanks for the help.

**Comment by tjvr** [comment]
No problem!
