### ISSUE TITLE
Stop generating rules as JSON

### ISSUE THREAD

**Issue by somebody1234** [Hardmath123/nearley#229]
`name` instead of `"name"` is not only shorter but more importantly makes rules easier to read in the generated code

**Comment by tjvr** [comment]
It's not clear what you're asking here.

**Comment by deltaidea** [comment]
I think the suggestion was this:

```Diff
- {"name": "main", "symbols": ["statement"], "postprocess": id}
+ {name: "main", symbols: ["statement"], postprocess: id}
```

**Comment by somebody1234** [comment]
Yeah, I have a fork where it's an array instead, not sure how much faster it is, if at all
