### ISSUE TITLE
Comparison with others js parsers

### ISSUE THREAD

**Issue by LagodViads** [Hardmath123/nearley#232]
Congratulations for your parser and its very usefull "unparsing" part.

Here is a simple suggestion about the readme : why not add a short comparison with other js parsers (Chevrotain, Parsimmon, ANTLR4, PEG.js, Jison, Ohm-js) mentioning design principles, originality (ambiguities) and speed ?  If I read "nearley is über-fast and really powerful" and then look at the test [here](https://sap.github.io/chevrotain/performance/), nearly does not seem so fast compared to other parsers. So this "Use Nearly if you..." comparison paragraph might help users to discriminate use cases where nearly does the best (maybe left recursion, ambiguities).

**Comment by tjvr** [comment]
The benchmark you linked to is misleading: JSON is a very simple language and very easy to parse. This gives the less powerful parsers an advantage. It also doesn't quite compare the same thing between each parser (some of them aren't building the parse tree).

I think the readme already does a good job of describing nearley. :-)
