### ISSUE TITLE
Post-processing fails when returning an object 

### ISSUE THREAD

**Issue by almosnow** [Hardmath123/nearley#235]
This is definitely a noob question but I couldn't find an answer in the docs on to why this wouldn't work.

Also, in the tutorial linked [0], there is an example of this behavior that gives an error:

    N -> [0-9]:+ {% d => { type: 'NUMBER', value:parseInt(d[0].join(''), 10) } %}

When nearley-test'ing that, I get:

    {"name": "N", "symbols": ["N$ebnf$1"], "postprocess": d => { type: 'NUMBER', value:parseInt(d[0].join(''), 10) }}
                                                                                      ^
    SyntaxError: Unexpected token :
        at createScript (vm.js:56:10)
        at Object.runInThisContext (vm.js:97:10)
        [...]

Has there been some API change or anything that I'm not aware of?

Thanks.

[0]: https://medium.com/@gajus/parsing-absolutely-anything-in-javascript-using-earley-algorithm-886edcc31e5e

**Comment by Hardmath123** [comment]
Ah, this isn't a nearley issue, but a JS issue. It's parsing the `{}`s as a block of statements rather than a JSON object for some reason. You can fix it by surrounding it in parentheses to force JS to parse it as an expression, like this:

```
d => ({ type: 'NUMBER', value:parseInt(d[0].join(''), 10) })
```

**Comment by almosnow** [comment]
Oooooh man, you're right!

> It's parsing the {}s as a block of statements rather than a JSON object for some reason.
Yeah, that's how arrow syntax works.

Thank you and sorry for bothering.

**Comment by Hardmath123** [comment]
No problem — it's a tricky JS quirk, and I'm glad I could help. :-)
