### ISSUE TITLE
CSV Example Only Works with Quoted Fields

### ISSUE THREAD

**Issue by knpwrs** [Hardmath123/nearley#237]
I've compiled the included CSV example and run into a problem with quoted fields.

The following input:

```
foo,bar,baz
foo,bar,baz
```

Produces the following output:

```js
[ { header: [ '', '', '' ], rows: [ [ '', '', '' ], [ '' ] ] } ]
```

While the following input:

```
"foo","bar","baz"
"foo","bar","baz"
```

Produces the following output:

```js
[ { header: [ 'foo', 'bar', 'baz' ],
    rows: [ [ 'foo', 'bar', 'baz' ], [ '' ] ] } ]
```

I've been trying to figure it out but at this point I'm just poking around trying to figure out how to write grammars.

**Comment by Hardmath123** [comment]
Sorry, that's a bug. Should be fixed now — thanks for reporting! Let me know if you run into any other issues.
