### ISSUE TITLE
Can't cope with large-ish input

### ISSUE THREAD

**Issue by pureformat** [Hardmath123/nearley#238]
I'm quite happy with the Javascript backend of Antlr, but its runtime is horrendously huge. So I figured I'd take Nearley for a spin.

However, while Antlr is happy to deal with my 5MB CSV file, Nearley stall for almost a minute before Node goes:

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

In general, Nearley seems to be a lot slower than Antlr and unable to handle large input. Any optimizations/tricks I can try?

I'm using the CSV grammar from the Nearley repository, latest version of everything, on macOS.

**Comment by pureformat** [comment]
Node test case:

```
		var nearley = require("./nearley");
		var grammar = require("./csv");
		var fs = require("fs");

		var p = new nearley.Parser(grammar.ParserRules, grammar.ParserStart);
		p.feed(fs.readFileSync("data-5mb.csv");
```

**Comment by tjvr** [comment]
- Make sure you're using the latest version of nearley
- I don't know if the CSV grammar is optimised at all—perhaps it uses right recursion, which can be slow?
- In particular, we generally recommend using a lexer/tokenizer: nearley is good for moderate to complex grammars, but in general you want to use a lexer with your parser. Lexers are good at stupid tasks like splitting up words.

We've just added lexer support, but it's not quite documented yet :-)

Perhaps if you're particularly interested in the CSV grammar, you could add your file to the benchmark suite? However I believe our CSV grammar is just intended as an example, and not particularly for production use; unless I suppose you have some quirky CSV format that an off-the-shelf CSV parser can't handle :-)

**Comment by pureformat** [comment]
I'm on the latest version, and my test input is extremely simple:

1,2,3
1,2,3
1,2,3
1,2,3
....

**Comment by Butterwell** [comment]
Given this simple (simplest?) line-oriented grammar:
main -> aline:* {% function(d) { return d[0] } %} 
aline -> %line {% function(d) { return d[0].value } %}
(full source attached)
[line.ne.txt](https://github.com/Hardmath123/nearley/files/1022574/line.ne.txt)

With a hand-built lexer that doesn't show up in profiling, parsing test_this, as generated by:
 var many = []
 for (var i=0; i<20000; i++) { many.push(i+"\n") }
 var test_this = many.join("")

Takes 9 seconds.  An equivalent grammar generated by peg.js takes 60ms, less than 1% of the time.

Chrome profiling shows the first half the time in Column.process => State.finish => arrpush and the second in Column.process => arrpush

**Comment by Hardmath123** [comment]
@tjvr can we hack the postprocessors of EBNF-modifier-generated-rules to generate linked lists compatible with the ones nearley generates when there is *no* postprocessor? That should fix @Butterwell's problem.

**Comment by tjvr** [comment]
@Butterwell I would suggest avoiding the EBNF modifiers in this case, and expanding the rule yourself. That way you can control how the list is allocated. If you can look at the generated code, you can see that the EBNF rule is using `arrpush`, which has quadratic behaviour:

```js
{"name": "main$ebnf$1", "symbols": ["main$ebnf$1", "aline"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
```

**Comment by Butterwell** [comment]
@tjvr Perhaps do a rewrite on :* and :+ so they translate into forms that don't use concat? For example, and I believe what you suggested:
main -> null        
        | lines           {% function(d) { return d[0] } %}
lines -> aline        {% function(d) { return d } %}
        | lines aline   {% function(d) { var a = d[0]; a.push(d[1]); return a } %}
aline -> %line      {% function(d) { return d[0].value } %}

300ms, a 30x improvement. Still 5x slower than peg.js, but usable.

**Comment by tjvr** [comment]
Unfortunately, that's not possible in general. nearley supports ambiguous grammars, and so we can't mutate the array in `arrpush`.

I'd recommend a linked list, or mutating the array if you're sure it can't be part of a different parse. :-)

**Comment by pureformat** [comment]
I recommend toning down the wording on http://nearley.js.org, because Nearley.js is not fast by any metric. In fact, almost any grammar I throw it at is consistently 10x slower than Antlr.

**Comment by Butterwell** [comment]
@tjvr The default structure without hand-crafted functions is effectively a linked list: [[[["a"],"b"],"c"],"d"], just with an easier prev than next function. :) 

I wasn't talking about mutating the array. I was talking about doing the same translation as I just did, but automatically. Translating (internally, conceptually), this:
```
main -> aline:*
```
to this:
```
main -> null
        | __aline_plus  {% function(d) { return d[0] } %}

__aline_plus -> aline       {% function(d) { return d } %}
        | __aline_plus aline {% function(d) { var a = d[0]; a.push(d[1]); return a } %}
```
With the added benefit the rewrite forces the use left recursion.

**Comment by tjvr** [comment]
@pureformat We disagree. It's true that nearley makes different tradeoffs than other tools, but it still has competitive performance. Even on [this misleading benchmark](http://sap.github.io/chevrotain/performance/) nearley is not 10x slower:

<img width="254" alt="screen shot 2017-05-23 at 20 26 22" src="https://cloud.githubusercontent.com/assets/639289/26372604/6a162a7c-3ff6-11e7-96b0-b1975ab4fd80.png">

---

@Butterwell Unfortunately that does still mutate the array `a` :( Thank you for you suggestion, though!

**Comment by Butterwell** [comment]
@tjvr You've admitted that :* and :+ are quadratic because of the use of .concat (essentially). My suggested method to fix the quadratic behavior is no good because of the mutation. Okay. Stop the pain some other way. If it's not possible some other way, I suggest you reconsider 1) the support of :* and :+, 2) mutation, in particular, in what very limited cases you can get away with mutation, 3) how to rewrite what arrpush does so it isn't quadratic,  and/or 4) how another level of indirection will fix all the problems :).

**Comment by pureformat** [comment]
Benchmarks are useless. I'm using Nearley and ANTLR4 on realworld grammars, and Nearley is dog slow. I really wanted to like Nearley, because Antlr has a huge runtime, but it's superslow on my real world stuff.

Sorry.

**Comment by tjvr** [comment]
> Stop the pain some other way

It's something we're pondering, but any fix would be backwards-incompatible. Something for v3 perhaps...

**Comment by FireCubez** [comment]
I'm having the same problem, I have about 50 lines of input, I feed each one individually, it goes to around line 15, then I stop getting messages, it hangs...
```input.split("\n").forEach((e, l) => {
    parser.feed(e);
    console.log("line " + l)
})```
I think im going to switch to another parser if this can't be fixed
