### ISSUE TITLE
Custom lexer + TypeScript = "Cannot find name" errors when compiling to JS

### ISSUE THREAD

**Issue by deltaidea** [Hardmath123/nearley#241]
- `node -v`: 7.10.0
- `npm -v`: 5.0.1
- `nearleyc -v`:  2.9.2 checked out from #234 (`b530e99`)

## Problem description

Nearley compiles `%foo` into TypeScript `lexer.has("foo") ? {type: "foo"} : foo`, and that `foo` at the end is not a known name. So when I compile TS to JS, I get this error: `error TS2304: Cannot find name 'foo'`.
I'm using [Moo lexer](https://github.com/tjvr/moo) and it provides the tokens, so `lexer.has(...)` is true.

TS does get compiled to JS, but the errors lead to failed CI builds. I could try and disable all errors for this one file, but obviously it's better to have this resolved upstream.

## Minimal example

- [`example.ne`](https://github.com/deltaidea/nearley-type-definitions-example/blob/master/example.ne)
- [`example.ts`](https://github.com/deltaidea/nearley-type-definitions-example/blob/master/example.ts) - compiled from `.ne`
- [`example.js`](https://github.com/deltaidea/nearley-type-definitions-example/blob/master/example.js) - compiled from `.ts`
- [`package.json`](https://github.com/deltaidea/nearley-type-definitions-example/blob/master/package.json)

## Proposed solution

I realize that there's no easy fix for this because it's not possible to infer at compile time which custom tokens will be defined at run time and which will be provided by a lexer.

The best backwards-compatible path is to add `declare var foo: any` at the top for every custom token name. This will silence the errors, even though they are kinda valid.

I can submit a PR if this is an acceptable solution.

**Comment by tjvr** [comment]
Ah, I hadn't realised TS wouldn't like that :-) Can you explain your fix? I'm not sure I understand what you're suggesting! But it sounds like a PR which includes those lines (just for TS!) would be quite welcome, thank you!

Minor point: moo supports `lexer.has` now. I should update that example...

**Comment by deltaidea** [comment]
Thanks for your time!

More explicitly about the solution:
- Get a list of all used custom tokens: `["foo", "bar"]`.
- Output this before the rules:
```TypeScript
declare var foo: any
declare var bar: any
```

TypeScript allows to "declare" which variables are guaranteed to be defined but are not in this file. In our case, we tell it to shut up about all usages of `foo` and `bar` and that they can be of any type.
This will not affect JS in any way, it's just for the happiness of the TS compiler.

**Comment by tjvr** [comment]
Sounds great! A PR adding this would be welcome. :-)

I suppose you'll just need to modify `generate.typescript` to output your `declare var...` lines for each token. Finding all the used tokens is a bit of a pain; you'll need to iterate over all the rules and look for symbols with a `token` property. *Ideally* you'd only do this if the `@lexer` option was in use, but I'm not sure how to detect that (and the `has()` bits themselves actually come from [compile.js](https://github.com/Hardmath123/nearley/blob/89a91317509d5c242248d14cc9c296b5f6050f7b/lib/compile.js#L129) which is kinda ew and all this needs refactoring but there we go). :-)
