### ISSUE TITLE
cannot make it work with next.js

### ISSUE THREAD

**Issue by freddi301** [Hardmath123/nearley#246]

**Comment by deltaidea** [comment]
Please describe your problem in detail and post a minimal example to reproduce it, or at least an error message.

**Comment by freddi301** [comment]
https://github.com/freddi301/kell

`npm run dev`

`localhost:3000/repl`

**Comment by deltaidea** [comment]
Thank you for the link! Could you please describe what you're trying to accomplish and what's going wrong? Please don't make us read through your whole codebase.

**Comment by freddi301** [comment]
I'm just writing a toy programming language.
I'm using https://github.com/lightblub/nearley-make.
I wrote a basic repl for the terminal, now i want write one for the browser.
But it gives me error about the 'fs' modules.
I tried to romeove the use of fs module in my sources, then another error about the fs module popped out due to nearley-make, it was an unused import (already filed an issue) and removed that, but now it gives me one more problem about the fs module in the nearley module, i tried also to instruct webpack to ignore it but more errors came out.
Is the node module of nearley ready to use in browser?

**Comment by deltaidea** [comment]
The simplest solution would be to compile the grammar into a JS file beforehand. You can either do it in `src/` like I show below, or put the `syntax.js` right into `.next`.

Add to "scripts" in `package.json`:

```JS
{
  "compile-grammar": "nearleyc src/syntax.ne -o src/syntax.js",
  // ...
}
```

Add to `.gitignore`:

```JS
src/syntax.js
```

Change `src/index.js`:

```Diff
- import nearleyMake from "nearley-make";
- import fs from 'fs';
- const grammar = fs.readFileSync('src/syntax.ne', 'utf-8');
+ import { Parser } from 'nearley';
+ import { ParserRules, ParserStart } from './syntax.js';
  export function parse(text: string): Term | Rules {
-   const parser = nearleyMake(grammar, { require });
+   const parser = new Parser(ParserRules, ParserStart);
    parser.feed(text);
    if (parser.results.length === 0) throw new Error('unecpected end of input');
```

---

Alternatively, you could try to add [this `fs.readFileSync` browserify transform](https://github.com/substack/brfs) as a Webpack loader using [`transform-loader`](https://github.com/webpack-contrib/transform-loader) in your [custom Next.js config](https://github.com/zeit/next.js#customizing-webpack-config). This way, your code would work both on the server with native `fs.readFileSync` and in the browser with file contents inlined as strings by the loader.

If you choose this solution and something goes wrong, you can check how [nearley-playground](https://github.com/bijection/nearley-playground) does it. They somehow dynamically compile a grammar from a textarea on the client-side.

Good luck! 😄

**Comment by Hardmath123** [comment]
Thanks for helping out with this issue, @deltaidea! I agree that the right solution here is indeed to compile the grammar ahead of time. nearley is built to work in both node and the browser — but the usage mechanisms are slightly different. :-)

**Comment by freddi301** [comment]
Thanks!
