### ISSUE TITLE
Case-insensitive string literals?

### ISSUE THREAD

**Issue by balbuf** [Hardmath123/nearley#249]
Hello!

I've been working on a [utility](https://github.com/balbuf/css-selector-inspector) that, among other things, parses CSS selector strings, and mostly I've been able to figure everything out in terms of putting together my grammar. The one thing I'm wondering about is string literals that are case-insensitive. Thankfully, there are only a couple of cases where I need to spell them out explicitly, so I've done what seems to be [a decent workaround](https://github.com/balbuf/css-selector-inspector/blob/master/src/selector-grammar.ne#L151), but would be terribly cumbersome (and easily error-prone) if I had many more literals or literals of much longer length:

```
[lL] [iI] [tT] [eE] [rR] [aA] [lL]
```

Is there another way to accomplish this?

The other thought I had, which again I would consider a work-around more than anything, would be to match a generic case-insensitive string and reject unwanted matches:

```
[a-zA-Z]:* {% (d, location, reject) => d[0].toLowerCase() === 'literal' ? d : reject %}
```

Any thoughts?

P.S. I looked at [gajus/scalpel](https://github.com/gajus/scalpel), which is what introduced me to nearley and inspired me to learn how to write some grammar and roll my CSS selector parser that would be more complete.

**Comment by deltaidea** [comment]
Why not just do `nthKeyword -> "odd" | "even"`

![image](https://user-images.githubusercontent.com/4950036/27513406-f7912ba4-597d-11e7-8111-b91f0c58209c.png)

P.S. That's the [nearley playground](https://omrelli.ug/nearley-playground/).

**Comment by deltaidea** [comment]
Using `reject` seems to be the more sane workaround, good job coming up with that!

You could use the [moo lexer](https://github.com/tjvr/moo) which is far easier to use and faster than the built-in lexer.

```JS
@{%
  const moo = require('moo');
  const mooLexer = moo.compile({
    eol: { match: /\r?\n/, lineBreaks: true },
    larrow: '<',
    rarrow: '>',
    literal: [ 'odd', 'even' ]
  });
%}
@lexer mooLexer

expression -> %larrow %literal %rarrow %eol:?
```

This will parse `<odd>` and `<even>`.
Keep in mind that these tokens (`%eol`, etc.) are given to you directly from moo, so they are objects, not strings: `{type, value, size, offset, lineBreaks, line, col}`. You can get the string like this: `main -> %literal {% d => d[0].value %}`

**Comment by tjvr** [comment]
I would avoid `reject` if possible—this will perform badly, since it will be called after every letter!

Using moo is generally recommended—we should really update the docs to reflect this.

Case-insensitive things are kind of awkward.
https://github.com/tjvr/moo/issues/46 might help a little? :-)

**Comment by Hardmath123** [comment]
Proposal: allow string literals like `"abc!"i` which desugar to `[Aa] [Bb] [Cc] "!"` in nearleyc.

**Comment by Hardmath123** [comment]
Actually, this would be very easy to implement. Up for grabs if someone wants to contribute the patch, otherwise I can probably do this tonight.

**Comment by tjvr** [comment]
@hardmath123 That won't play nicely with `@lexer` :/

**Comment by Hardmath123** [comment]
*shrug* Why not? You shouldn't ever be mixing `@lexer` and case-insensitive string literals.

**Comment by marco-m-alves** [comment]
Same issue here. Was this solved?

**Comment by Hardmath123** [comment]
Okay, I went ahead and implemented it via 3a6ba845674e829843d8c25b5ce1c4bcf9fd7dd8 

Version 2.10.2 should have case-insensitive strings, which you can create with `"string"i`.

**Comment by Hardmath123** [comment]
(Tim, hope that's okay with you. If I just broke some lexer stuff, let me know.)

**Comment by tjvr** [comment]
Sounds fine as long as it's an error to mix case-insensitivity and @lexer? :-)

**Comment by Hardmath123** [comment]
Yeah, that should be an error. We should probably check for that.

**Comment by tjvr** [comment]
This is added and documented, so I'm gonna close this. :-)

**Comment by samuelgoto** [comment]
> Sounds fine as long as it's an error to mix case-insensitivity and @lexer? :-)

Ugh, just ran into this and had to dig into the issues until I found the reason. 

> This is added and documented, so I'm gonna close this. :-)

Documenting is great, but if there was a way to programatically detect this (using case insentiive strings and @lexers at the same time), that would probably be best.
