### ISSUE TITLE
Better way of doing client-side compilation [optimisation, question] 

### ISSUE THREAD

**Issue by fauxneticien** [Hardmath123/nearley#256]
I'm aware of the nearley playground [source code](https://github.com/bijection/nearley-playground), but I don't have any familiarity with React/etc. to be able to quite grasp how it is compiling the grammars (e.g. the text in the the Basic Grammar/Fancier Grammar tabs) in the browser.

What I've done is mimicked what lines 50-52 do in [`nearleyc.js`](https://github.com/Hardmath123/nearley/blob/master/bin/nearleyc.js), then run `eval()` on the generated Javascript string. See demo at [https://codepen.io/anon/pen/JyRLXq?editors=0010#0](https://codepen.io/anon/pen/JyRLXq?editors=0010#0).

```
$("#compile").click(function() {
   var nearleyc = new nearley.Parser(grammar.ParserRules, grammar.ParserStart, { "keepHistory" : true });
   var ne_data  = $("#grammar_def").val();

   nearleyc.feed(ne_data);
   var c = Compile(nearleyc.results[0], { alreadycompiled:false });
   var js_str = generate(c, "my_compiled_grammar");

   eval(js_str);
   alert("Compiled as my_compiled_grammar!");
})
```

I'm sure there's a better/recommended way of compiling grammars without using `nearleyc` in the command line (without React/etc.)—I was hoping you could point me in the right direction?

Thanks!

**Comment by bd82** [comment]
Please keep in mind that some security policies disallow evals
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
So while such an approach is good for a playground or a website you control,
it may not be relevant for all **productive** flows.

**Comment by fauxneticien** [comment]
@bd82 — I'm looking to use this inside an Electron app in production, so perhaps to some extent this counts as 'under my control'? Would be entirely glad if anyone could point me a way of doing this without the `eval()` call.

**Comment by bd82** [comment]
@fauxneticien 

Sorry I have no idea about electron and content security policies. 😢 
I've heard of issues in things such as Chrome extensions, but I have no idea
if and how this is relevant in electron.

Related search shows 24 issues in electron.
https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20CSP

**Comment by tjvr** [comment]
You need the `eval` call if you want to compile a `.ne` file, because of how generate is currently written.

Have a look at how we compile grammars in [`shared.js`](https://github.com/Hardmath123/nearley/blob/master/test/_shared.js) without using the `nearleyc` CLI tool. That might help :-)

**Comment by deltaidea** [comment]
I'm quite certain there's no way to avoid `eval` because you need to execute postprocessors at some point.

In Electron, the best solution is to do this is in the main process, the one where you create `BrowserWindow` and can use `require`. Just use the `nearley` npm package there.

Use [IPC messaging](https://github.com/electron/electron/blob/master/docs/api/ipc-main.md) to send the grammar from the page to the main process and to send any information back.

**Comment by deltaidea** [comment]
Let's include this in the docs: [preview](https://github.com/deltaidea/nearley/blob/improve-docs/docs/using-in-frontend.md).

I hope @fauxneticien and @tjvr are OK with using parts of both solutions (codepen and shared.js) in the docs where other people will potentially copy-paste the example.

**Comment by fauxneticien** [comment]
Thanks for the feedback all! Happy for the codepen example to be used in the docs.

**Comment by tjvr** [comment]
Nice example @deltaidea! :-)
