### ISSUE TITLE
Consider switching docs with website

### ISSUE THREAD

**Issue by tjvr** [Hardmath123/nearley#262]
@Hardmath123 wants to swap the website with the README/docs (from https://github.com/Hardmath123/nearley/pull/254#issuecomment-320044984):

> I propose something more radical: currently, the README is a behemoth of a tutorial/documentation/README crossover, while the webpage is what convinces you to use nearley. I think they should be swapped. The README should contain most of the contents of index.html (and some other stuff). /www should contain the docs, split up into chunks that make sense:
> 
> - Tutorial
> - Using lexers
> - nearley on the front-end
> - Performance tips
> - etc.
> 
> There's probably a way to coax github into rendering those markdown documents into a nice self-contained webpage, perhaps with Jekyll or something.

I'm not convinced. I quite like the current arrangement: everything is Markdown files, easily viewed and accessible on GitHub.

**Comment by deltaidea** [comment]
I agree that Markdown is better. When reading docs, I don't want to leave GitHub. I can see how a pure documentation page can be less confusing for people not familiar with the GitHub interface (navbar, menus and such), but `.md` is so easy to change, and to read locally.

There're two good options: leave everything as is, or duplicate docs on both GitHub and on the website.

Frankly, I don't see the need for the website at all.

**Comment by Hardmath123** [comment]
https://github.com/Hardmath123/nearley/commit/13befbb08ac439e4151d288bbf17ca4fc3957736 started the process for this. More work needed.

**Comment by tjvr** [comment]
In #270 we're gonna add sidebar navigation to the site!
