### ISSUE TITLE
We lost a couple dependent projects during the monster merge

### ISSUE THREAD

**Issue by deltaidea** [Hardmath123/nearley#263]
See e3576809902ca7b721cc21f58c34e1ac3c74539b.

**Comment by tjvr** [comment]
Looks like those are still in master? :-) https://github.com/Hardmath123/nearley/blob/master/index.html#L274-L278

**Comment by deltaidea** [comment]
Ah, I didn't even notice there's a duplicate list on the website. It got quite out of sync. Oh well.

**Comment by Hardmath123** [comment]
index.html _is_ the website. The website's list of dependents is meant to be a large curated list of good nearley projects. It's meant to say (1) look! people use nearley! and (2) if you need help, check out how these people solve their problems.

The README's list of dependents is there to show you that nearley can be used in many ways.
