### ISSUE TITLE
What is the difference between lexer, tokenizer, scanner?

### ISSUE THREAD

**Issue by deltaidea** [Hardmath123/nearley#265]
AFAIK, they are all the same thing, at least for the purposes of nearley. It might be a good idea to mention that somewhere early on. Currently, the docs just suddenly switch between these words, which is confusing when you don't know what these are and the docs are trying to explain it.

**Comment by tjvr** [comment]
From [Lexical Analysis (WP)](https://en.wikipedia.org/wiki/Lexical_analysis):

> lexical analysis is the process of converting a sequence of characters...into a sequence of tokens... . A program that performs lexical analysis may be termed a **lexer**, **tokenizer**, or **scanner**, though scanner is also a term for the first stage of a lexer

So yes, they're roughly the same thing. IMHO "scanner" is an unusual term for a lexer. Although "scannerless" parsing (parsing without a tokenizer/lexer stage) has a specific meaning; you wouldn't say "lexerless".

So. I think introducing Moo as a "tokenizer (aka lexer)" would be fine. Calling the internal interface `Lexer` is fine. Calling the default (no tokenizer) setup "scannerless" is also fine. :-)

**Comment by Hardmath123** [comment]
> when you don't know what these are and the docs are trying to explain it

I think the solution here is that the docs should first tell you what these are! :P
