### ISSUE TITLE
Unordered groupings of optional nonterminals

### ISSUE THREAD

**Issue by aweary** [Hardmath123/nearley#273]
Hey there! I have a (potentially basic) question about how to best define a set of unordered, optional terminals. For context, I'm trying to fix an issue with [scalpel](https://github.com/gajus/scalpel) which is a CSS3 selector parser.

With CSS simple selectors you have a set of selectors (id, class, attributes, pseudo-classes, etc) that can appear after an optional type selector (`div`, `span`, etc) or a universal selector (`*`). Here is [the grammar defined by the spec](https://www.w3.org/TR/css3-selectors/#grammar):

```
simple_selector_sequence
  : [ type_selector | universal ]
    [ HASH | class | attrib | pseudo | negation ]*
  | [ HASH | class | attrib | pseudo | negation ]+
  ;
```

So this means that any of these selectors can appear in any order. For example, these are all valid:

```css
/* type -> class -> id */
div.class#foo
/* universal -> id -> class */
*#foo.class
/* class -> attr value -> id */
.class[attr="foo"]#foo
/* id -> class -> attr presence */
#foo.class[attr]
```

The issue with the [current definition for a simple selector in scalpel](https://github.com/gajus/scalpel/blob/master/src/grammar.ne#L39-L41) is that its ordered.

```
selectorBody ->
    typeSelector:? idSelector:? classSelector:* attributeValueSelector:* attributePresenceSelector:* pseudoClassSelector:* pseudoElementSelector:? {% (d, i, reject) => { const selectors = flatten(d); if (!selectors.length) return reject; return selectors; } %}
  | universalSelector idSelector:? classSelector:* attributeValueSelector:* attributePresenceSelector:* pseudoClassSelector:* pseudoElementSelector:? {% flatten %}
````

So for example, with this definition, the ID selector must come before the class selector, which is not to spec.

So my question is how can I express the grammar defined in the spec (posted at the top) using nearley? Thanks for the great lib and the help!

**Comment by aweary** [comment]
I've tried defining a new nonterminal:

```
simpleSelector ->
  classSelector
| attributeValueSelector
| attributePresenceSelector
| pseudoClassSelector
| pseudoElementSelector
```

and then doing:

```
selectorBody ->
  typeSelector:? simpleSelector:? {...}
```

But it won't parse selectors with more than one selector (`div.foo` works but `div.foo#bar` fails)

**Comment by Hardmath123** [comment]
Perhaps I'm misunderstanding your issue, but wouldn't replacing `simpleSelector:?` with `simpleSelector:*` in your last example solve the problem?

**Comment by aweary** [comment]
Hey @Hardmath123, I had tried that initially but got some errors, but on second look it seems like the errors are just due to some processing functions that needed to be updated. `simpleSelector:*` seems to work great. Thanks for the help!

**Comment by Hardmath123** [comment]
No problem, glad I could help. :-)
