### ISSUE TITLE
Custom Token Matcher with Parameter

### ISSUE THREAD

**Issue by alijaya** [Hardmath123/nearley#274]
Hi, is it possible to make custom token matcher with parameter?
Suppose this example:
I have series of tokens that's not a string, it's an object like {a: "asdf", b: 12}, and I want to match the content of "a" to be "asdf"...
It would be great if I could do it like this:
@{%
const matchA = function(v) {
  return { test: o => o.a == v };
};
%}
main -> %matchA("asdf")

**Comment by Hardmath123** [comment]
Hmm, I think an easy solution here would just be to create fresh matchers in your `@{%%}` block:

```
const matchA = function(v) {
return { test: o => o.a == v };
};
const matchA_asdf = matchA("asdf");
const matchA_ghjk = matchA("ghjk");
…

main -> %matchA_asdf
```

Since you have a finite number of references to that matcher in any grammar, this will work.

@tjvr, other ideas?

**Comment by tjvr** [comment]
@Hardmath123 No, there's no clever way of doing this.

Which property on your token are you trying to match?

**Comment by alijaya** [comment]
So I try to create a parser for TeX, and the token in TeX is a character and a category character for that character, so it has 2 properties each token. And from the documentation, the parser could match the character only, the category only or both. So that's why I need custom token matcher with parameter.

**Comment by Hardmath123** [comment]
So it looks like the solution in my comment [here](https://github.com/Hardmath123/nearley/issues/274#issuecomment-323821622) will solve your problem for now. If not, let me know, but for now I'm closing this issue. :-)
