### ISSUE TITLE
Ambiguity again

### ISSUE THREAD

**Issue by rumkin** [Hardmath123/nearley#275]
I have such ambiguous rule:
```
value ->
"true"
| "false"
| var
| number

var -> [a-zA-Z]:+
```

This produce ambiguous output for `true` and `false` values. how to avoid this?

**Comment by Hardmath123** [comment]
You have two options:

1) You can use the `reject` feature; see the example here: https://nearley.js.org/docs/grammar#postprocessors

2) You can use a lexer; see the examples here to get started: https://nearley.js.org/docs/tokenizers

Using a lexer is our recommended way of solving this problem, but if you already have a big grammar, then the `reject` feature is an easy fix. :-)

**Comment by rumkin** [comment]
I've decided this with hacky postprocessor.

**Comment by Hardmath123** [comment]
Great! Glad I could help.
