### ISSUE TITLE
Using Nearley with Typescript

### ISSUE THREAD

**Issue by notsonotso** [Hardmath123/nearley#276]
Are the @types outdated? I installed 2.10.5 of nearley, but the latest types is 2.9.0.

When running, I get

    var lexer = rules.Lexer;
                     ^
    TypeError: Cannot read property 'Lexer' of undefined

Reproduce with:

    import * as nearley from 'nearley';
    const grammar = require('../grammar.js');

    // Exception happens here
    const parser = new nearley.Parser(nearley.Grammar.fromCompiled(
                                      <nearley.Rule[]>(grammar.rules), "file"));
    parser.feed("test 1 2 3");
    console.log(parser.results);

**Comment by notsonotso** [comment]
@deltaidea Could you take a look?

**Comment by notsonotso** [comment]
Actually, probably not TS related?

require('../grammar.js') returns output, but Lexer: undefined

    { Lexer: undefined,
      ParserRules: <lots of stuff here>
    }

ideas?

**Comment by Hardmath123** [comment]
Not sure what's up here. @deltaidea made the "@types" thing; I don't really know how it works.

Just in case it's a nearley-side issue, could you also post your grammar.ne file and the generated grammar.js file?

**Comment by notsonotso** [comment]
@Hardmath123 sure:

Minimal repro:

```
@builtin "whitespace.ne"
@builtin "number.ne"

id -> [a..zA..Z0-9]
```

Generated parser:

```
// Generated automatically by nearley
// http://github.com/Hardmath123/nearley
(function () {
function id(x) {return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": function(d) {return null;}},
    {"name": "__$ebnf$1", "symbols": ["wschar"]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": function(d) {return null;}},
    {"name": "wschar", "symbols": [/[ \t\n\v\f]/], "postprocess": id},
    {"name": "unsigned_int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "unsigned_int$ebnf$1", "symbols": ["unsigned_int$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "unsigned_int", "symbols": ["unsigned_int$ebnf$1"], "postprocess": 
        function(d) {
            return parseInt(d[0].join(""));
        }
        },
    {"name": "int$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "int$ebnf$1$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "int$ebnf$1", "symbols": ["int$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "int$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "int$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "int$ebnf$2", "symbols": ["int$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "int", "symbols": ["int$ebnf$1", "int$ebnf$2"], "postprocess": 
        function(d) {
            if (d[0]) {
                return parseInt(d[0][0]+d[1].join(""));
            } else {
                return parseInt(d[1].join(""));
            }
        }
        },
    {"name": "unsigned_decimal$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "unsigned_decimal$ebnf$1", "symbols": ["unsigned_decimal$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "unsigned_decimal$ebnf$2$subexpression$1$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "unsigned_decimal$ebnf$2$subexpression$1$ebnf$1", "symbols": ["unsigned_decimal$ebnf$2$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "unsigned_decimal$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "unsigned_decimal$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "unsigned_decimal$ebnf$2", "symbols": ["unsigned_decimal$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "unsigned_decimal$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "unsigned_decimal", "symbols": ["unsigned_decimal$ebnf$1", "unsigned_decimal$ebnf$2"], "postprocess": 
        function(d) {
            return parseFloat(
                d[0].join("") +
                (d[1] ? "."+d[1][1].join("") : "")
            );
        }
        },
    {"name": "decimal$ebnf$1", "symbols": [{"literal":"-"}], "postprocess": id},
    {"name": "decimal$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decimal$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "decimal$ebnf$2", "symbols": ["decimal$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decimal$ebnf$3$subexpression$1$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "decimal$ebnf$3$subexpression$1$ebnf$1", "symbols": ["decimal$ebnf$3$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decimal$ebnf$3$subexpression$1", "symbols": [{"literal":"."}, "decimal$ebnf$3$subexpression$1$ebnf$1"]},
    {"name": "decimal$ebnf$3", "symbols": ["decimal$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "decimal$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decimal", "symbols": ["decimal$ebnf$1", "decimal$ebnf$2", "decimal$ebnf$3"], "postprocess": 
        function(d) {
            return parseFloat(
                (d[0] || "") +
                d[1].join("") +
                (d[2] ? "."+d[2][1].join("") : "")
            );
        }
        },
    {"name": "percentage", "symbols": ["decimal", {"literal":"%"}], "postprocess": 
        function(d) {
            return d[0]/100;
        }
        },
    {"name": "jsonfloat$ebnf$1", "symbols": [{"literal":"-"}], "postprocess": id},
    {"name": "jsonfloat$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "jsonfloat$ebnf$2", "symbols": ["jsonfloat$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "jsonfloat$ebnf$3$subexpression$1$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "jsonfloat$ebnf$3$subexpression$1$ebnf$1", "symbols": ["jsonfloat$ebnf$3$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "jsonfloat$ebnf$3$subexpression$1", "symbols": [{"literal":"."}, "jsonfloat$ebnf$3$subexpression$1$ebnf$1"]},
    {"name": "jsonfloat$ebnf$3", "symbols": ["jsonfloat$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "jsonfloat$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$1", "symbols": [/[+-]/], "postprocess": id},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$2", "symbols": ["jsonfloat$ebnf$4$subexpression$1$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "jsonfloat$ebnf$4$subexpression$1", "symbols": [/[eE]/, "jsonfloat$ebnf$4$subexpression$1$ebnf$1", "jsonfloat$ebnf$4$subexpression$1$ebnf$2"]},
    {"name": "jsonfloat$ebnf$4", "symbols": ["jsonfloat$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "jsonfloat$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat", "symbols": ["jsonfloat$ebnf$1", "jsonfloat$ebnf$2", "jsonfloat$ebnf$3", "jsonfloat$ebnf$4"], "postprocess": 
        function(d) {
            return parseFloat(
                (d[0] || "") +
                d[1].join("") +
                (d[2] ? "."+d[2][1].join("") : "") +
                (d[3] ? "e" + (d[3][1] || "+") + d[3][2].join("") : "")
            );
        }
        },
    {"name": "id", "symbols": [/[a..zA..Z0-9]/]}
]
  , ParserStart: "id"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
```

Error:

```
{ Lexer: undefined,
  ParserRules: [ { name: 'id', symbols: [Object] } ],
  ParserStart: 'id' }
../node_modules/nearley/lib/nearley.js:171
    var lexer = rules.Lexer;
                     ^

TypeError: Cannot read property 'Lexer' of undefined
```

**Comment by deltaidea** [comment]
You're type-checking `node_modules` which is generally useless and can lead to errors outside of your code. If you'd share your `tsconfig.json` and `tslint.json`, I could help find the reason `node_modules` is even included in the checking process. It's ignored by default.

**Comment by notsonotso** [comment]
@deltaidea sure

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "outDir": "out",
        "lib": [
            "es6"
        ],
        "sourceMap": true,
        "rootDir": "."
    },
    "exclude": [
        "node_modules",
        ".vscode-test"
    ]
}
```

No tslint set up yet.

**Comment by notsonotso** [comment]
@deltaidea tsconfig above. But... the error happens when I run "node out/myparser.js", not when compiling. tsc works just fine.

**Comment by deltaidea** [comment]
You're right, and I'm wrong.

Thanks for the repro code! Turns out, generating JS and TS parsers gives different exports. 🤦‍♂️ 
Exports from TS: `{ Lexer, ParserRules, ParserStart }` (plus the types)
Exports from JS: `{ grammar: { Lexer, ParserRules, ParserStart }}`

This is an issue with TS generator, I'd say. Because JS is the canonical implementation.

**Comment by notsonotso** [comment]
Are you saying I can't use Nearley with Typescript?

**Comment by Hardmath123** [comment]
@notsonotso Aha, I think I see the issue. Try using it without `fromCompiled`.

**Comment by Hardmath123** [comment]
(Also, paging @tjvr who almost certainly knows what's up.)

**Comment by notsonotso** [comment]
@Hardmath123 you mean

```
const parser = new nearley.Parser(grammar.rules, "file");
```

?

Unfortunately same result.

**Comment by deltaidea** [comment]
@notsonotso For now, just import it differently if you're using `@preprocessor typescript`:

```TypeScript
import * as grammar from "./grammar";

const parser = new nearley.Parser(nearley.Grammar.fromCompiled(grammar));
```

**Comment by Hardmath123** [comment]
I'm confused — you are you using the `@preprocessor typescript` feature? Because your minimal example grammar above doesn't.

**Comment by notsonotso** [comment]
Not use @preprocessor at all, no

Dunno what that is.

Also, import * as grammar from "./grammar"; fails with "Cannot find module", while require definitely finds it.

**Comment by Hardmath123** [comment]
Ah, I see. To confirm: you want to use your actual parser in TypeScript; you don't care about using TypeScript in the postprocessors of your grammar?

**Comment by notsonotso** [comment]
@Hardmath123 correct

**Comment by notsonotso** [comment]
You guys need a Gitter room ;)

**Comment by deltaidea** [comment]
Here's what I understand: you have a grammar, which you compile to a plain JS file. You then require this file in your TS code. And this basic code from the docs fails?

```TS
const nearley = require("nearley");
const grammar = require("./grammar.js");
const parser = new nearley.Parser(nearley.Grammar.fromCompiled(grammar));
```

**Comment by Hardmath123** [comment]
@notsonotso Hah, maybe. I like the issues because they're publicly-viewable/indexed, and usually conversations aren't so fast-paced! Anyway, I had considered snagging #nearley on freenode, but I don't think there's enough of a community for it to be helpful. :-)

**Comment by notsonotso** [comment]
@Hardmath123 Ohhhhhh, I passed `grammar.rules` to fromCompiled, not grammar.

It works with only grammar. Thank you!

Is the typedef's wrong? They say

```
export namespace Grammar {
    function fromCompiled(rules: Rule[], start: string): Grammar;
}
```

**Comment by deltaidea** [comment]
Yes, I wrote that before I had a good grasp on the implementation details. I was just starting and wrote that as I went along.

**Comment by notsonotso** [comment]
@deltaidea OK, I guess I shouldn't be using @types/nearley yet then?

**Comment by notsonotso** [comment]
@Hardmath123 for the record, all Gitter rooms are publicly indexed / searchable. Not fast paced at all, works really well for Q&A. But hey, just a suggestion :)

**Comment by deltaidea** [comment]
Everything is perfectly usable, just the types are not great. I'd suggest doing `grammar as any` as a workaround, until someone (maybe you?) has time to fix that line in the types.

**Comment by notsonotso** [comment]
That renders it pointless

**Comment by Hardmath123** [comment]
Yes, I took a look and it does seem like https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/nearley/index.d.ts#L62 is wrong.

> Everything is perfectly usable, just the types are not great. I'd suggest doing grammar as any as a workaround, until someone (maybe you?) has time to fix that line in the types.

Wait… isn't the point of type annotations to, err, y'know, provide correct types? Or am I completely misunderstanding what you're trying to do with `@types/nearley`?

@notsonotso Since @types/nearley is broken, I would recommend looking at how the folks at Chalmers wrote Shrdlite. They used typescript+nearley for quite a while, and it worked extremely well. The relevant code fragments are here: https://github.com/ChalmersGU-AI-course/shrdlite-course-project/blob/master/Parser.ts#L27 :-)

---

By the way, to be clear, the nearley team didn't implement/takes no responsibility for third-party nearley tooling like `@types/nearley` — this really should have been an issue on _that_ repository. I'm going to leave this open for now until @notsonotso gets it working; however, if you have new issues involving `@types/nearley`, please open a ticket there. Feel free to @mention me or tjvr if you need _nearley_-side assistance.

**Comment by notsonotso** [comment]
@Hardmath123 thanks for the link, very useful!

One last question for now... I'm getting Out Of Memory very easily when testing some grammars. Is there a way to debug the reason? 

Pretty sure it blow up because of recursion in the grammar?

**Comment by Hardmath123** [comment]
One way to get started is to use the `nearley-test` utility that ships with nearley. Try it with small inputs to see whether the parse table is getting too large in some cases. https://nearley.js.org/docs/tooling#nearley-test-exploring-a-parser-interactively

Or, you could post your grammar here and we can take a look. In that case, do make a separate issue — this one's confusing enough as it is! :-)

**Comment by notsonotso** [comment]
@Hardmath123 I have many small questions :) That's where Gitter rocks. I'd rather not create an issue every time I have a question.

**Comment by Hardmath123** [comment]
> I'd rather not create an issue every time I have a question.

Ah, but I'd rather you _do!_ That's how we've been running the issues page, and it works great for us. Turns out we love answering easy questions — it's the hard bug reports that trip us up… :P

**Comment by notsonotso** [comment]
OK, most projects hate using issues for that. If that's okay for you, I'm fine with it too :D
