### ISSUE TITLE
Post processor for tokens

### ISSUE THREAD

**Issue by notsonotso** [Hardmath123/nearley#285]
I use moo and have this rule:

    list -> %leftParen expressions %rightParen

I need a post processor action as soon as %leftParen is seen. 

I tried putting a post processor directive between %leftParen and expressions, but that is not allowed.

Does this mean I have to introduce a Nearly rule like

    leftParen -> %leftParen {% ... %}

?

**Comment by Hardmath123** [comment]
You can also do `leftParen -> (%leftParen {% … %})`.

But I caution you about writing postprocessors that have side-effects — nearley assumes postprocessors are pure and can be run in any order, as many times as it wants, with any input.

**Comment by notsonotso** [comment]
> But I caution you about writing postprocessors that have side-effects 

@Hardmath123 so how am I supposed to create an AST?

**Comment by Hardmath123** [comment]
Take a look at the examples, such as https://github.com/Hardmath123/nearley/blob/master/examples/csv.ne
