### ISSUE TITLE
Why I quit using Nearley

### ISSUE THREAD

**Issue by notsonotso** [Hardmath123/nearley#288]
So... the docs are lacking at best, and the only way to ask questions is to submit an issue. No slack, no Gitter, no mailing list. When I start a conversation with an issue, my first question is answered with something like "look at the CVS example" (which didn't answer my question). Then the issue is closed, before my follow-up questions.

Community is everything, and this time it didn't work out.

It's a shame. I had some issues with buggy TypeScript definition files. This was fixed incredibly quickly. But you need to get better at helping newcomers.

**Comment by Hardmath123** [comment]
Ahh, looks like you have a, well, unique set of expectations from open-source. Sadly our already-very-stretched-thin team doesn't have the resources to satisfy them. Hope you can find better service elsewhere.
