### ISSUE TITLE
Ambiguity not evident in nearley-test output

### ISSUE THREAD

**Issue by spurcell** [Hardmath123/nearley#292]
I have a grammar producing multiple parsings of an input, implying ambiguity, but when I run nearley-test on the input, it outputs two identical parse trees. That doesn't seem correct to me; shouldn't the parsings differ if there's more than one way to parse the input? Thanks!

**Comment by Hardmath123** [comment]
Not necessarily — if you are using empty "null" rules, then all sorts of bad things can happen. As a simple example,
```
a -> null "a" | "a" null
```
is ambiguous with input "a", as shown:
```
$ nearley-test -i a <(nearleyc <(echo 'a -> null "a" | "a" null'))
Table length: 2
Number of parses: 2
Parse Charts
Chart: 0
0: {a →  ● "a"}, from: 0
1: {a →  ● "a"}, from: 0

Chart: 1
0: {a → "a" ● }, from: 0
1: {a → "a" ● }, from: 0


Parse results: 
[ [ 'a' ], [ 'a' ] ]
```

Another possibility is that you are using postprocessors to map different "raw" trees to the same output. You can compile grammars with the `--nojs` option to disable them and see these "raw" trees, which should differ.

**Comment by spurcell** [comment]
Of course, the nulls! Thanks for the clear and quick answer. I don't have any explicit nulls in my grammar but they're implicit in lots of ? and * rules.

I had already deleted the postprocessor logic to make sure that it wasn't obscuring the answer (the nojs flag throws away my lexer so I can't use that).

Some way to see which rule exactly is where the parse "forked" would be extremely helpful.

**Comment by Hardmath123** [comment]
> Of course, the nulls! Thanks for the clear and quick answer.

Glad I could help. :-)

**Comment by tjvr** [comment]
> Some way to see which rule exactly is where the parse "forked" would be extremely helpful.

We think so too! I'm not sure if it's captured in an issue anywhere, but this is definitely something @Hardmath123 and I are thinking about.
