### ISSUE TITLE
Error, loop on certain grammars

### ISSUE THREAD

**Issue by tomjridge** [Hardmath123/nearley#293]
I went to the online playground.

I typed in the grammar:

E -> E E E | "1" | null

Chrome (my browser) then hung.

Obviously there are infinitely many parse trees, but Earley parsing per-se should be able to parse this.

I have only tried this example, and now I can't try the playground because it always hangs when I go to that page (presumably the javascript recovers the example, and then hangs).

**Comment by tjvr** [comment]
> Obviously there are infinitely many parse trees, but Earley parsing per-se should be able to parse this

Sorry, but (at least for now) nearley generates all the parse trees during parsing; so when there's an infinite number, parsing will never finish.

As a tip, you should be able to manually reset the playground by running `localStorage.clear()` on any page on the same domain as the playground (e.g. a 404 page). Not being able to recover sounds like a bug with the playground, which isn't maintained by us! :-)

**Comment by tomjridge** [comment]
OK, thanks.
