### ISSUE TITLE
New tool for the nearley.js.org website?

### ISSUE THREAD

**Issue by ryanhaney** [Hardmath123/nearley#295]
@Hardmath123

Posted [this issue](https://github.com/Hardmath123/hardmath123.github.io/issues/18). Respectfully continuing the conversation here.

My goal with [nearley-template](https://github.com/appology/nearley-template) is to provide a starter-kit for launching your own parser powered by nearley that is ready for grammar customization, testing and publishing to npm. When I created [resp-parser](https://github.com/appology/resp-parser), it was evident that the only [resp-parser](https://github.com/appology/resp-parser) specific part of the project was the grammar file. Additional nearley-powered parser packages would require similar boilerplate code, so why not automate?

Perhaps [nearley-template](https://github.com/appology/nearley-template) can be a new addition to the ["Other Tools" section of the nearley.js.org website](https://nearley.js.org/docs/tooling)?

Thanks for your consideration :-)

**Comment by Hardmath123** [comment]
Ryan, could you write a small blurb in the format of "Other Tools"?

And Tim, what do you think?

**Comment by ryanhaney** [comment]
How about:

**Node** users can quickly create a project that is ready for testing and publishing with [nearley-template](https://github.com/appology/nearley-template).

Thanks again!

**Comment by tjvr** [comment]
@Hardmath123 Sounds good to me. Certainly can't hurt :-)

**Comment by Hardmath123** [comment]
Okay, done. Thanks for the submission!
