### ISSUE TITLE
web app freezing a lot

### ISSUE THREAD

**Issue by HedvigS** [Hardmath123/nearley#300]
Hi! I really like Nearley, and I was setting up some toy examples to teach others [using the web browser playground app](http://omrelli.ug/nearley-playground/). But, it keeps freezing a lot. I fact, now it's freezing right away even with the most simple little grammars. What could be going on? The grammar is _extremely_ simple in this case and it ran fine just moments ago. But now it does nothing but freeze, in chrome, in firefox, in private browsing.. yeah it just keeps freezing.

The script that is failing is:
http://omrelli.ug/nearley-playground/dist/client.bundle.js:20

What could be up?

Here's an example of a grammar I've put in when it's been freezing

MIDSOMER_MURDERS_PLOT -> LOCAL PROFESSION FOUND DEAD PLACE SUSPICION SUSPECT ANGRY BLAMED THREAT THREATENED
LOCAL -> "A local "
PROFESSION -> "linguist" | "philosopher" | "novelist"
FOUND -> " is found "
DEAD -> "drowned" | "strangled" | "dead" | "tortured to death" | "hanged" | "battered" | "suffocated" | "shot" | "knifed" | "nuked"
PLACE -> " in the coffee shop." |" in the swimming pool." | " after band practice."| " behind the primary school."
SUSPICION -> " Suspicion falls on the village "
SUSPECT -> "baker" | "pastor" | "mailman" | "florist" | "nerd" | "twins"
ANGRY -> ", angry that the "
BLAMED -> "new wind farm" | "pig" | "pub" | "decline in newspaper reading" | "metric system"
THREAT -> " might threaten "
THREATENED -> "the village fabric." | "what little sexual tension the village has left." | "the Old Inn." | "the cow farm."

**Comment by HedvigS** [comment]
It fails on line 20, but I don't know what the trouble is . I'm assuming copy-pasting in that bit of the script is not necessary (it's very large).

**Comment by HedvigS** [comment]
For some unknown reason, it now works in Chrome Incognito. I have done nothing different.

**Comment by Hardmath123** [comment]
Hedvig, you probably want to take this up with the owner of nearley-playground (@bijection).

**Comment by HedvigS** [comment]
Aha, I see. Will do. Thanks.
