### ISSUE TITLE
Probably an error in parsing numbers

### ISSUE THREAD

**Issue by AntonShan** [Hardmath123/nearley#303]
```
node version: v8.6.0 (checked on v8.2.1 before - results are the same)
npm version: 5.3.0
nearley version: 2.11.0
```

I have following grammar in my stc.ne file
```
@{%
	const {fromPairs} = require('lodash')
%}
@builtin "number.ne"
@builtin "string.ne"

# CATALOG -> OBJECT_DEFINITION:* {% id %}

OBJECT_DEFINITION -> NAME __ unsigned_int __ dqstring __ GROUP __:* {%
    ([type,, number,, name,, properties]) => ({
    	type,
    	name,
    	number,
    	properties
    })
%}

VALUE -> BOOLEAN
    | FLOAT_POINT
    | dqstring
    | GROUP
    | ARRAY

GROUP -> "{" __:? GROUP_PROPERTY:* "}"
	{% data => fromPairs(data[2]) %}

GROUP_PROPERTY -> NAME __ VALUE __:?
	{% data => [ data[0], data[2][0] ] %}

ARRAY -> "[" __:? ARRAY_ELEMENT:* "]"
	{% data => data[2] %}

ARRAY_ELEMENT -> VALUE __:?
	{% data => data[0][0] %}

NAME -> [\w] {% id %}
        | NAME [\w] {% data => data.join('') %}

BOOLEAN -> "true" {% data => data[0] === 'true' %}
	| "false"	{% data => data[0] === 'true' %}

FLOAT_POINT -> jsonfloat {% id %}

__ -> WSCHAR:+
	{% d => null %}

WSCHAR -> [\s]
	{% id %}
```

And I have a following file as input
```
SomeType 9000 "Some Catalog Object" {
  SomeString  "Some String Value"
  SomeNumber  69
  SomeNegativeNumber  -69
  SomeFloatPointValue  1.618
  SomeNegativeFloatPointValue  -1.618
  SomeBooleanProperty  true
  ArrayOfNumbers  [ 3.14 2.56 42 1 100500 1e+5 1.220462e+7]
  ArrayOfStrings  [
    "smfn;sdhf;dsafha sdasd aasdas asd f"
    "xzksaljdads"
    "k"
  ]
  NestedGroup  {
    GroupChildProperty  "Hello"
    AnotherGroupChildProperty  false
  }
}
```

And I got this as a result
```
{
    type: "SomeType",
    name: "Some Catalog Object",
    number: 9000,
    properties: {
        SomeString: "Some String Value",
        SomeNumber: 69,
        SomeNegativeNumber: -69,
        SomeFloatPointValue: 1.618,
        SomeNegativeFloatPointValue: -1.618,
        SomeBooleanProperty: true,
        ArrayOfNumbers: [
            3.1,
            4,
            2.56,
            42,
            1,
            10,
            0,
            50,
            0,
            100000,
            1.2204,
            620000000
        ],
        ArrayOfStrings: [
            "smfn;sdhf;dsafha sdasd aasdas asd f",
            "xzksaljdads",
            "k"
        ],
        NestedGroup: {
            GroupChildProperty: "Hello",
            AnotherGroupChildProperty: false
        }
    }
}
```

As we can see, `.properties.ArrayOfNumbers` array contains completely wrong numbers compared to input.

Expected result: `[3.14, 2.56, 42, 1, 100500, 100000, 12204620]`
Actual result: `[3.1, 4, 2.56, 42, 1, 10, 0, 50, 0, 100000, 1.2204, 620000000]`

I spent a few hours trying to figure out whether my grammar file have wrong rules or it's a bug in a library and now I'm asking for assistance to figure out where problem really is.

The whole project is here: https://github.com/AntonShan/nearley-stc-parser

**Comment by tjvr** [comment]
I can’t quite follow your grammar, but here are some things to try:

- Pull in just the builtin rules you need, and make sure they do what you expect
- Or, we strongly recommend you use a tokenizer; they tend to be easier and faster!
- Finally, make sure there’s only one result; perhaps your grammar is accidentally ambiguous? :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Hardmath123** [comment]
It's ambiguous:

```
ARRAY -> "[" __:? ARRAY_ELEMENT:* "]"
	{% data => data[2] %}

ARRAY_ELEMENT -> VALUE __:?
	{% data => data[0][0] %}
```

Notice that this does not _require_ whitespace between array members. Thus, nearley doesn't know how to parse something like `[123]`: it could be `[1,2,3]` or `[12,3]` or `[1,23]` or `[123]`.

In particular, your example `[ 3.14 2.56 42 1 100500 1e+5 1.220462e+7]` causes confusion because `3.14` can also be parsed as `3.1, 4` and `1.220462e+7` can be parsed as `1.2204, 62e+7`.

Solution: make it `__` instead of `__:?` in `ARRAY_ELEMENT`.

**Comment by tjvr** [comment]
We really should push tokenizers harder, they help avoid this sort of thing. Then again, I thought we already recommend them pretty strongly in the docs...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AntonShan** [comment]
Ok, I got it. Now trying to make things with Moo.
