### ISSUE TITLE
Free memory in completed states

### ISSUE THREAD

**Issue by Hardmath123** [Hardmath123/nearley#31]
Completed states in the table can be `null`'d and fed to the gc. This ought to free up memory (someone correct me if I'm wrong).

**Comment by matthew-dean** [comment]
Yes. Setting any object to null should get garbage collected eventually.

**Comment by Hardmath123** [comment]
Hmm, yeah, I need to get around to implementing this. The thing is, you need to be kind of careful about which states you nullify.

**Comment by hackwaly** [comment]
Sliding window could be used on the table to avoid consuming unnecessaory memory.

**Comment by wizzard0** [comment]
BTW, this must be an option because it will conflict with restarting (rewinding) a parser

**Comment by tjvr** [comment]
> this must be an option because it will conflict with restarting (rewinding) a parser

Indeed. :-)

**Comment by Hardmath123** [comment]
85ca34b should have fixed this. (Though, in the future, this will become optional because it breaks certain things — such as rewinding and nearley-test.)
