### ISSUE TITLE
Wrong error messages because of shared lexer.

### ISSUE THREAD

**Issue by ozum** [Hardmath123/nearley#327]
Hi,

I'm using nearley with moo lexer as described in nearley documents. When I created two distinct parser instances using `new.nearley.Parser()`, they seem to share same lexer.

Because of shared lexer, wrong error messages are thrown. `parser.lexer.formatError()` generates messages from different parser.

## Reproduction of case:

`node v8.8.1`, `nearleyc v2.11.0`, `npm v5.5.1`

`grammar.ne` file:
```
@{%
  const moo   = require("moo");
  const lexer = moo.compile({
    word: /[a-z]+/
  });
%}

@lexer lexer

main -> %word
```

`index.js` file
```js
const nearley = require('nearley');
const grammar = require('./grammar');

const parserA   = new nearley.Parser(nearley.Grammar.fromCompiled(grammar));
const parserB   = new nearley.Parser(nearley.Grammar.fromCompiled(grammar));
parserA.feed('a');
parserB.feed('b');

// Expected: 'a'
// Got:      'b'
console.log(require('util').inspect(parserA.lexer.buffer, { depth: 1 }));

// Expected and got: 'b'
console.log(require('util').inspect(parserB.lexer.buffer, { depth: 1 }));

// Expected: Error at line 1 col 1: a
// Got:      Error at line 1 col 1: b
console.log(parserA.lexer.formatError(parserA.results[0][0], 'Error'));

// Expected and got: Error at line 1 col 1: b
console.log(parserA.lexer.formatError(parserB.results[0][0], 'Error'));
```

## Possible Solution
Although I'm not sure about performance of compiling a new lexer everytime, allowing `@lexer` to be a function which returns a new lexer everytime may be solution.

I hope that someone suggests a better solution than this.

```
@{%
  const moo   = require("moo");
  const lexer = () => moo.compile({ word: /[a-z]+/ });
%}

@lexer lexer

main -> %word
```

**Comment by tjvr** [comment]
This is a quirk in `formatError`, which I don’t think is fixable. The intention is that you call `formatError` right after you find a parse error.

We could call `lexer.clone()` every time, but that would have a performance impact due to re-compiling the RegExp.

I think if you really want to use it this way, you should call `info = lexer.save()` and also store `lexer.buffer`. You can then call `lexer.reset(buffer, info)`. This is how nearley is using the lexer internally.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ozum** [comment]
@tjvr my concern is not only related to `formatError`. `lexer` object stores state. In this case nearley parser objects share a stateful object which has state from another unrelated nearley parser object.

```js
console.log(parserA.lexer === parserB.lexer); // True
```

Besides of performance implications, previously proposed solution at least gives decision to the developer.

`@lexer lexer` could behave according to typeof `lexer`. If it is an object it behaves as usual, but if it is a function, it can execute function and use returned value as a lexer. Just my two cents.

**Comment by tjvr** [comment]
> nearley parser objects share a stateful object which has state from another unrelated nearley parser object

No. The parser stores the state of the lexer, and uses `reset` to control the lexer state before parsing, on every call to `feed()`.

**Comment by ozum** [comment]
What I mean is, I can access buffer of another object.

```js
// I can access lexer buffer of parserB using parserA
// Expected: 'a'
// Got:      'b'
console.log(parserA.lexer.buffer, { depth: 1 });
```

**Comment by tjvr** [comment]
Sure. That won't affect a nearley parser though; because they store their own state, they won't stand on each other's toes.

**Comment by ozum** [comment]
Ok. Thanks for the responses. If it is possible, just consider adding function support please. I'm closing the topic.
