### ISSUE TITLE
Postprocessor is never called

### ISSUE THREAD

**Issue by blainehansen** [Hardmath123/nearley#332]
I'm using `nearley 2.11.0`, `node v9.3.0`, and `npm 5.5.1`.
I'm getting a strange bug, where a postprocessor for one of my rules is never called. I've stripped down my grammar and am still getting the problem.

Parsing this simple input:
```css
.thing

```
With this grammar:
```ne
program -> classSelector %newline:?

classSelector -> %dot identifier {% ([_, identifier]) => identifier %}

identifier -> %identifier | %dashlessIdentifier {% ([identifier]) => {
	console.log('identifier')
	return identifier.value
} %}
```

The `console.log('identifier')` never outputs anything, and that rule doesn't have any transformation in the final result:
```
[
  [
    {
      "type": "identifier",
      "value": "thing",
      "text": "thing",
      "offset": 1,
      "lineBreaks": 0,
      "line": 1,
      "col": 2
    }
  ],
  {
    "type": "newline",
    "value": "\n",
    "text": "\n",
    "offset": 6,
    "lineBreaks": 1,
    "line": 1,
    "col": 7
  }
]
```

I'm confident this problem is unrelated to my lexer. When I run it by itself on this input, it outputs these tokens:
```
{ type: 'dot',
  value: '.',
  text: '.',
  toString: [Function: tokenToString],
  offset: 0,
  lineBreaks: 0,
  line: 1,
  col: 1 }
{ type: 'identifier',
  value: 'thing',
  text: 'thing',
  toString: [Function: tokenToString],
  offset: 1,
  lineBreaks: 0,
  line: 1,
  col: 2 }
{ type: 'newline',
  value: '\n',
  text: '\n',
  toString: [Function: tokenToString],
  offset: 6,
  lineBreaks: 1,
  line: 1,
  col: 7 }
```

Thank you.

**Comment by blainehansen** [comment]
Ah, I just figured it out. Now I see that for "or" rules a postprocessor has to be provided for each one.

```ne
@{%
...
function consoleAndValue([identifier]) {
	console.log('identifier')
	return identifier.value
}
%}

...

identifier ->
	%identifier {% consoleAndValue %}
	| %dashlessIdentifier {% consoleAndValue %}
```

I think this should be more clearly explained in the docs, that section has no mention of it.
https://nearley.js.org/docs/grammar#postprocessors

It would also be nice to have a syntax for defining postprocessors for any of the several "or" rules.

**Comment by Hardmath123** [comment]
You can just do `a -> (b | c | d) {% postprocessor %}`.
