### ISSUE TITLE
Error when parsing comment in last line without line end

### ISSUE THREAD

**Issue by Nopik** [Hardmath123/nearley#333]
If I have a comment in last line of the grammar file, but the file doesn't end with endline, `nearleyc` crashes with some cryptic error.

I.e. `nearleyc` chokes on file with such hexdump:

```
$ xxd test.ne
00000000: 6120 2d3e 2022 2322 0a23                 a -> "#".#
```

**Comment by Hardmath123** [comment]
Duplicate of #128. @tjvr how much do we care about this? I still think all files _should_ be newline-terminated.

**Comment by Nopik** [comment]
Closed as duplicate.
