### ISSUE TITLE
Limiting array depth (and other questions)

### ISSUE THREAD

**Issue by matthew-dean** [Hardmath123/nearley#52]
Next question-- (Sorry for all the questions, I'm trying to evaluate this for a large project, would love to talk to you about it.)

When using the example javascript.js, or even in writing short grammar of my own, the parser seems to generate unnecessarily deep array structures. For instance, with parsing something like this:

```
(function() {
  var blah = 'blah';
});
```

I get a structure like this:

![screen shot 2015-03-24 at 7 45 50 am](https://cloud.githubusercontent.com/assets/414752/6804418/ba0b93c6-d1fa-11e4-8500-f19cbea8033b.png)

Most of the arrays contain nothing but another array. Even from the text output, you can see it's creating arrays with no value.
![screen shot 2015-03-24 at 7 53 19 am](https://cloud.githubusercontent.com/assets/414752/6804446/e2decca0-d1fa-11e4-88d1-51d14ba3b6d2.png)

Since each array increases the number of JS objects in memory, is there a way to keep this structure a little flatter and eliminate empty arrays (or arrays with one value which is another array)? Seems like matching entities like variable names or values could be pushed as a single value. Does nearley support that?

**Comment by Hardmath123** [comment]
Yes! You're looking for the "postprocessor" feature. Read about "postprocessors" in the README. :-)

**Comment by Hardmath123** [comment]
(The reason javascript.js doesn't use postprocessors is because I haven't implemented them. It'll take me 20-30 minutes, max.)

**Comment by JacobEdelman** [comment]
I had it so it outputted completely flat output, meaning it would just output the input. I imagined it being used for building macros. The reason why it has so much nesting is because (as a loose examples) "1+1;" might be a statement which is a statement_expression which is an expression which is an addition_expression.... and so on many layers deep. Simplifying it with post processors would be trivial, it would just depend on exactly what you wanted the output to be.

**Comment by matthew-dean** [comment]
Ah, okay, I figured it was something like that. So it segments everything by... expression I guess? But then you collapse /  said expressions, I take it. Okay, that makes a certain kind of sense. If it's "as expected", it's a little less scary. :)

**Comment by matthew-dean** [comment]
Related: I'm coming along with writing the grammar. I read about postprocessors, but that still left me with a few questions. Such as:

1. What does ```{% id %}``` do? It's tangentially referenced, or referenced as "you should probably know this already".
2. If my parsing output has multiple copies of input throughout the array, is that a sign of ambiguous grammar? Or... does that just happen without proper post processing.
3. Similarly, when I run nearley-test with my input, it parses, but produces 21 charts. What do "charts" mean? Is "1" the target number of charts?

See below:
```
// input: 
.a .b, .c { b: 123; }

// parser results
[ [ [],
    [ [ [ [ [ [ '.', [ null, [ 'a' ], [] ] ] ],
            [ [ [],
                [ [ ' ' ] ],
                [],
                [ [ '.', [ null, [ 'b' ], [] ] ] ] ] ],
            null ],
          [ [ [],
              ',',
              [ [ ' ' ] ],
              [ [ [ '.', [ null, [ 'c' ], [] ] ] ],
                [],
                null ] ] ] ],
        [ [ ' ' ] ],
        [ '{',
          [ [ ' ' ] ],
          [ [ [ [ [ null, [ 'b' ], [] ],
                  [],
                  ':',
                  [ [ ' ' ] ],
                  [ [ [ [ [ '1', '2', '3' ] ] ] ],
                    [] ] ] ],
              [ ';' ] ] ],
          [ [ ' ' ] ],
          '}',
          null ] ] ],
    [] ],
  [ [],
    [ [ [ [ [ [ '.', [ null, [ 'a' ], [] ] ] ],
            [ [ [],
                [ [ ' ' ] ],
                [],
                [ [ '.', [ null, [ 'b' ], [] ] ] ] ] ],
            null ],
          [ [ [],
              ',',
              [ [ ' ' ] ],
              [ [ [ '.', [ null, [ 'c' ], [] ] ] ],
                [],
                null ] ] ] ],
        [ [ ' ' ] ],
        [ '{',
          [ [ ' ' ] ],
          [ [ [ [ [ null, [ 'b' ], [] ],
                  [],
                  ':',
                  [ [ ' ' ] ],
                  [ [ [ [ [ '1', '2' ] ] ] ],
                    [ [ [], [ [ [ [ '3' ] ] ] ] ] ] ] ] ],
              [ ';' ] ] ],
          [ [ ' ' ] ],
          '}',
          null ] ] ],
    [] ],
  [ [],
    [ [ [ [ [ [ '.', [ null, [ 'a' ], [] ] ] ],
            [ [ [],
                [ [ ' ' ] ],
                [],
                [ [ '.', [ null, [ 'b' ], [] ] ] ] ] ],
            null ],
          [ [ [],
              ',',
              [ [ ' ' ] ],
              [ [ [ '.', [ null, [ 'c' ], [] ] ] ],
                [],
                null ] ] ] ],
        [ [ ' ' ] ],
        [ '{',
          [ [ ' ' ] ],
          [ [ [ [ [ null, [ 'b' ], [] ],
                  [],
                  ':',
                  [ [ ' ' ] ],
                  [ [ [ [ [ '1' ] ] ] ],
                    [ [ [], [ [ [ [ '2', '3' ] ] ] ] ] ] ] ] ],
              [ ';' ] ] ],
          [ [ ' ' ] ],
          '}',
          null ] ] ],
    [] ],
  [ [],
    [ [ [ [ [ [ '.', [ null, [ 'a' ], [] ] ] ],
            [ [ [],
                [ [ ' ' ] ],
                [],
                [ [ '.', [ null, [ 'b' ], [] ] ] ] ] ],
            null ],
          [ [ [],
              ',',
              [ [ ' ' ] ],
              [ [ [ '.', [ null, [ 'c' ], [] ] ] ],
                [],
                null ] ] ] ],
        [ [ ' ' ] ],
        [ '{',
          [ [ ' ' ] ],
          [ [ [ [ [ null, [ 'b' ], [] ],
                  [],
                  ':',
                  [ [ ' ' ] ],
                  [ [ [ [ [ '1' ] ] ] ],
                    [ [ [], [ [ [ [ '2' ] ] ] ] ],
                      [ [], [ [ [ [ '3' ] ] ] ] ] ] ] ] ],
              [ ';' ] ] ],
          [ [ ' ' ] ],
          '}',
          null ] ] ],
    [] ] ]
```
Obviously, I'd want to get rid of empty arrays, semi-colon terminators, spaces, nulls and braces in the AST. How do I condense the AST to the "target" entities?

**Comment by Hardmath123** [comment]
A lot of good questions here!

1 - `{% id %}`: recall that post-processors are just JavaScript functions which are fed the parsed array for processing. `id` is a pre-defined "constant" function which returns the first element of an array. That is, we define `function id(x) {return x[0]; }` somewhere for you. This lets you write something like:

```
document -> program {% id %}
```

rather than

```
document -> program {% function(d) {return d[0]; } %}
```

Note that without the post-processor, nearley's output using that grammar will be wrapped in an array, because as far as it's concerned, all nonterminals' expansions are an array—even those with just one element. :-)

2 - Yes, that means you have some ambiguity. Each member of the top-level list is a valid parsing of your input with the grammar. Looking at your pasted output, I see that the only difference between these parsings is the way "123" is broken up as digits—**I suggest you double-check the part of your grammar that parses a number**.

3 - nearley-test is not as documented as it should be. As such, though, #charts should correspond to the number of characters in the input—not some metric to minimize. In theory, you'd want to minimize the number of rows in each chart, too, but don't worry about that. It won't be a significant performance boost.

I'm glad to see your grammar's coming along well! Keep me posted, and don't hesitate to ask any questions you might have. Seeing these misconceptions is actually really helpful to me when I design new features or write documentation. :-)

Cheers!

**Comment by Hardmath123** [comment]
Here's an example of using a post-processor to condense the arrays:

```
thing -> "a" "b" "c"
```

Without postprocessors, when run on "abc", this results in `["a", "b", "c"]`.

With a postprocessor, we can do something like:

```
thing -> "a" "b" "c" {% function(d) {return "A thing:" d[0] + d[1] + d[2];} %}
```

When you run that on "abc", you get the output `"A thing:abc"`.

**Comment by matthew-dean** [comment]
Okay, so now I have a concern. I came here to say, "Never mind, I don't think it's ambiguity because when I started putting in postprocessing, it eliminated the duplicates."

So now my worry is: is the grammar still ambiguous, but I'm hiding the problem because of post-processing? All I did was start returning objects with labels so I could see what was happening. As soon as I did that, I only got one permutation for the number value. o_O

I actually have the number value collapsing down to just:
```
[ [ { num: '123' } ] ] ] ],
```
... from the original result. My goal is to get to the most performant parsing possible, so I don't want to hide issues.

**Comment by Hardmath123** [comment]
Hmmm… that shouldn't be happening. But, in any case, if nearley returns only one result, then it's unambiguous. There's *no* postprocessed-value-equality-testing magic going on.

Again, it's really hard for me to guess what's up without looking at your actual grammar. As I said, grammar-writing is tricky, tricky stuff and you can get caught up in subtleties very easily! :-)

Finally: it's probably worth writing a grammar in its entirety first, before you try to optimize it. Unlike many other things, it's pretty easy to optimize a grammar once it's written.

**Comment by matthew-dean** [comment]
Ah. Well, here's what I have so far if you want to take a look. https://gist.github.com/matthew-dean/67891922dd5b78b4214c - It's for the Less language (the CSS preprocessor-- I'm part of the core team, so I'm researching ways to do faster parsing).

I'm having more fun than I thought I would solving this puzzle, so thanks so much for getting me past the initial roadblocks!

**Comment by Hardmath123** [comment]
Whoo, that's amazing! You can't imagine how gratifying it is to see all those fancy syntactic sugars I added to nearley be used in the wild. :D

**Comment by matthew-dean** [comment]
Well, it's not in use YET. The whole team makes those decisions (these fine people here - http://lesscss.org/about/), not just me, and I can imagine some reluctance to replacing the entire parsing component, so I want to get it to a point to generating a benchmark comparison with our existing parser. My instinct is that this your parser generator will be much faster than: https://github.com/less/less.js/blob/master/lib/less/parser/parser.js but I can't yet prove it.

But, as an example, look at the code for recognizing an element:
```
e = parserInput.$re(/^(?:\d+\.\d+|\d+)%/) ||
      parserInput.$re(/^(?:[.#]?|:*)(?:[\w-]|[^\x00-\x9f]|\\(?:[A-Fa-f0-9]{1,6} ?|[^A-Fa-f0-9]))+/) ||
      parserInput.$char('*') || parserInput.$char('&') || this.attribute() ||
      parserInput.$re(/^\([^&()@]+\)/) ||  parserInput.$re(/^[\.#:](?=@)/) ||
      this.entities.variableCurly();
```
Now, I suck at regex, and I know nothing about manually optimizing tokenizing and parsing, but it turns out I'm decent at writing grammar. So maybe I can pull this off. :smile: (The team talked about the possibility of generating the parser as one idea to address performance, so I said I would go off and research.)

Plus, if I finish this, Less would have an (official) defined grammar for the first time, which would help for other people who are maintaining ports.
