### ISSUE TITLE
Unrolling regexes

### ISSUE THREAD

**Issue by Hardmath123** [Hardmath123/nearley#57]
@JacobEdelman claims we can take full regexes in a grammar and compile them down to nearley automatically. I believe him, so I hereby assign this to him.

**Comment by JacobEdelman** [comment]
Will do. Timing depends on APs I have coming up and running a CS contest (both in the next week or so). So it might take me a bit until I can start but once I do get the time it shouldn't be too difficult.

**Comment by Hardmath123** [comment]
Issue seems dead. Also, feature is not worth it; can't see a place where it would be useful.
