### ISSUE TITLE
Tool to test if a grammar with a sample input file is ambiguous

### ISSUE THREAD

**Issue by bobbybee** [Hardmath123/nearley#61]
It has been shown that testing whether or not a grammar is ambiguous automatically is impossible / close to it. However, many ambiguities will show up in a sufficiently complex test file. I'd like a simple program that can be attached to a nearleyc build script to run the grammar with a given test file: if there are no parsings / an error parsing, the script raises an error, if there are ambiguities, the script also raises an error. If there is a single, unique parsing, the script gives a return code of 0 / no output.

Would make developing grammars a bit less painful, maybe.

**Comment by bojidar-bg** [comment]
@bobbybee That's (somewhat) simple to make with a node.js script...
E.g. (All of it untested, should work though)
````javascript
var nearley=require("nearley");
var child_process = require("child_process");
var fs = require("fs");
child_process.spawnSync("nearleyc",["grammer.ne","-o","tmp_grammer.js"]);

var grammer = require("tmp_grammer.js");
var parser = new nearley.Parser(grammar.ParserRules, grammar.ParserStart);
var results = parser.feed(fs.readFileSync("test.txt", "utf8"));

if(result.length == 1) {
  process.kill(0);
} else {
  process.kill(1);
}
````

**Comment by Hardmath123** [comment]
Issue seems dead; also trivial to implement yourself.
