### ISSUE TITLE
Why is the generated JS so verbose?

### ISSUE THREAD

**Issue by matthew-dean** [Hardmath123/nearley#64]
This is not meant to be a criticism but rather, I'm wondering why the generated JS is so "human-readable" and preserves all the named tokens. Is there any reason why the JS file generated from the grammar needs to be readable? Nearley doesn't need to know the names of the tokens, does it? Is that better for testing?

I was just taking a look at the parser file for javascript.js, and I think you could probably reduce the generated code to maybe 1/4 the size. And you could probably reduce the memory footprint by prototyping objects. ( `new Literal("w")` vs `{ "literal": "w" }`.  Objects that have the same "shape" can be optimized by the JIT compiler, whereas `{ "literal": "w" }` and `{ "literal": "h" }` won't necessarily be detected as having the same shape, IIRC.)  

(Also, the nearley parser then could perform different actions on symbols based on a matching type, rather than reading the property name "literal".)

.... I suppose you're going to make me write this, lol.

**Comment by matthew-dean** [comment]
Actually, I wonder if it'd be even faster to generate an enum for literals that consists of a single object that maps used literals to their numeric equivalents for ultra-fast comparison. As in:

```
var Literal = {
  w:  119,
  h: 104
};
...
{"name": "TokenName", "symbols": [ Literal.w, Literal.h ]},
```
Although each Rule could probably be optimized as well.

**Comment by matthew-dean** [comment]
Something like this:

```
{"name": " string$18", "symbols": [{"literal":"-"}, {"literal":"-"}], "postprocess": function joiner(d) {
        return d.join('');
    }},
    {"name": "UnaryOperator", "symbols": [" string$18"]},
    {"name": "UnaryOperator", "symbols": [{"literal":"+"}]},
    {"name": "UnaryOperator", "symbols": [{"literal":"-"}]},
    {"name": "UnaryOperator", "symbols": [{"literal":"~"}]},
    {"name": "UnaryOperator", "symbols": [{"literal":"!"}]},
```
... could probably have at least duplication removed and be like:
```
    new Rule(Token.string_18, [{ "symbols": [Literal.DASH, Literal.DASH], "postprocess": function joiner(d) {
        return d.join('');
    }]),
    new Rule(Token.UnaryOperator, [
     { "symbols": [Token.string_18] },
     { "symbols": [Literal.PLUS] }, 
     { "symbols": [Literal.DASH] },
     { "symbols": [Literal.TILDE] },
     { "symbols": [Literal.EXCLAMATION_POINT] } ] )
```

**Comment by Hardmath123** [comment]
Hey @matthew-dean 

This isn't something I've thought too much about, since nobody has written a grammar large enough for this to be an issue yet. I think the JIT point you bring up is by far the most important since it might be a significant speed boost.

Initially, of course, back in the days of yore when there was no .ne language, I wrote the initial (subsequently bootstrapped) grammar in the JS object format *by hand*, and so it needed to be verbose and easy to debug.

> .... I suppose you're going to make me write this, lol.

If you have the time, then that would be amazing! PRs are always welcome here. :-)

**Comment by matthew-dean** [comment]
The only problem with me doing this is I haven't gotten my grammar to work yet :cry:. Rewriting the JS output would make more sense when testing against a working grammar. I suppose though I could use the JavaScript one, but I think you've said in the past that it may have issues, no? Is there a support group where I could talk about my feelings re: nearley?

**Comment by Hardmath123** [comment]
> The only problem with me doing this is I haven't gotten my grammar to work yet

:-(

Anything I can help with?

> Rewriting the JS output would make more sense when testing against a working grammar.

There exist a couple nice, large in-the-wild grammars you can play with. Nearley's own bootstrapped grammar is pretty stable. [Shrdlite](https://github.com/AI-course-TIN172-DIT410/shrdlite-course-project/blob/master/grammar.ne) and [milk-lang](https://github.com/yishn/milk-lang/blob/master/grammar.ne) are two others.

> I suppose though I could use the JavaScript one, but I think you've said in the past that it may have issues, no?

Yeah, someday over the river @JacobEdelman will good-ify it. :-)

> Is there a support group where I could talk about my feelings re: nearley?

If you need, uh, counseling, you can pm me on IRC/Freenode (`hardmath123`). I can register `#nearley` if more people want to chat.

(Generic emotional support when Earley parsing gets you down is available at `#marpa` from the amazing @jeffreykegler, King of the Earley Parsers.)

**Comment by matthew-dean** [comment]
Are you on Twitter? You could DM me on https://twitter.com/matthewdeaners.

**Comment by Hardmath123** [comment]
No, sorry, I don't do social media. You can email me at Hᴀʀᴅᴍᴀᴛʜ123@ɢᴍᴀɪʟ.ᴄᴏᴍ (in lower-case).

**Comment by tjvr** [comment]
> Nearley doesn't need to know the names of the tokens, does it?

If we want to output sensible error messages (`Expected string`), then the names of the tokens are useful.

> Objects that have the same "shape" can be optimized by the JIT compiler, whereas { "literal": "w" } and { "literal": "h" } won't necessarily be detected as having the same shape, IIRC

Actually, V8 should share pseudoclasses between plain objects too!

---

My feelings about all this are that yes, you could shave a few bytes off the file size by using integers instead of names; but the difference will disappear after gzipping anyway, so why make your life difficult? :)
