### ISSUE TITLE
Calculator demo using right recursion...

### ISSUE THREAD

**Issue by bojidar-bg** [Hardmath123/nearley#65]
At https://github.com/Hardmath123/nearley/blob/master/examples/calculator/arithmetic.ne#L64 
````
	| [\s] _    {% function(d) {return null; } %}
````
This chokes with about 500 spaces.... Unlike this:
````
	| _ [\s]    {% function(d) {return null; } %}
````

**Comment by Hardmath123** [comment]
Ah, yes, makes sense. Do you want to make a PR with that change? (You could probably do it from within Github's interface!)

**Comment by bojidar-bg** [comment]
@Hardmath123 Ok...
