### ISSUE TITLE
JS preprocessors

### ISSUE THREAD

**Issue by bojidar-bg** [Hardmath123/nearley#67]
I'm quite accustomed to CoffeeScript, so I like to use it here and there. It would be nice if I can use a custom preprocessor with nearley (e.g. Babel, CoffeeScript, 5to6, PromisedLand...).

**Comment by Hardmath123** [comment]
I don't know how that would be implemented. Is there a way to instruct a preprocessor to only process code in `{% %}`'s?

**Comment by bojidar-bg** [comment]
@Hardmath123 we can simply pass the code between the {% %} to the preprocessor.

Also for coffeescript, we can wrap the non-coffee code in ``, and it won't be parsed. I'm not sure about the other preprocessors. (BTW, promisedLand shoud already work, as it is a superset of JS)

**Comment by Hardmath123** [comment]
Hmm, doesn't that require you to know which preprocessor to use ahead of time?

**Comment by bojidar-bg** [comment]
@Hardmath123 we can pass it as cmd line option to the compiler. Another option will be to place it on top of the file, e.g.:
``
@preprocessor coffee
@{% combine=(d)->d.join("") %}

w -> "1" "10" "asdf":+ {% combine %}
``

**Comment by Hardmath123** [comment]
The latter sounds better. Are you open to implementing this yourself? It'll take me a while because I'm busy with school stuff—but the actual code should be really simple.

**Comment by bojidar-bg** [comment]
@Hardmath123 well, I might try to do something this weekend, but don't expect too much.

*Hint: I'm currently making an atom grammar for nearley :smile:*
