### ISSUE TITLE
Move nearley.js and generated grammars to strict mode

### ISSUE THREAD

**Issue by ipelovski** [Hardmath123/nearley#77]
First I want to thank you for this library. It made me able to experiment freely with the syntax of my toy language. It saved me a lot of time.

Now to the point of this post: while I was making small change here and there in the code I noticed that the nearly.js file and the generated grammar js file are not in strict mode. Adding the 'use strict' directive made the code ~2x faster when parsing my grammar on node.js 4.0. This may not be the case for other grammars and other environments, but I think it is worth trying.

**Comment by Hardmath123** [comment]
Oh, wow, a 2x increase in speed is _amazing_! I did a code review against https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode and it looks like nearley is strict-mode compatible. I'll make the necessary changes and push an update asap. Thanks!

**Comment by Hardmath123** [comment]
(EDIT: Actually, looks like using strict mode breaks certain things. Hmm. Do you have a working copy with strict mode enabled which I can merge in as-is?)

**Comment by ipelovski** [comment]
Sorry, I don't have one. I had problem with `this`, maybe on this line https://github.com/Hardmath123/nearley/blob/master/lib/nearley.js#L146. I passed `this` as a second argument to `forEach`:
```
rules.forEach(function(r) {...}, this);
```

**Comment by Hardmath123** [comment]
Hmm, yeah, it appears "use strict" does some messing about with `this`. I'll work on getting this working, but feel free to file a PR if you get it working before I do. :-)

**Comment by beaugunderson** [comment]
I have a very simple grammar for parsing emojis and adding `'use strict';` to the generated file doesn't seem to provide any speedup.

**Comment by ipelovski** [comment]
Beau Gunderson, try to add `'use strict';` to lib/nearley.js file too. I'm experimenting with a simple language very similar to Smalltalk. The problem is that Nearley takes too much time to parse larger chunks of code (I mean no offense here, Nearly is a wonderful library). What I did was to create a simple lexer/tokenizer to feed the parser with tokens. That sped the parsing a lot. I also tried to parse a sentence by sentence (e.g. `foo: bar. bar: foo.' is split to two chunks `foo: bar.` and `bar: foo.`). This was slower for small pieces of code but was 2-3 times faster when parsing 50-100kb chunks of code. I'm still not able to get the speed of the Marpa parser (https://github.com/jeffreykegler/libmarpa) (what I read was that the author was able to parse tens of thousands lines of code per second). Maybe I'm doing something wrong, I just don't know, since I'm still a beginner in these things.

**Comment by Hardmath123** [comment]
Ah, @ipelovski, you're trying to pit a turtle against a hare. Marpa runs natively in C, whereas Nearley runs in a browser. Also, Marpa has had many many years of aggressive optimizations from the brilliant Jeffrey Kegler. There's really no competition: Marpa will always be faster by a gigantic margin, despite all our efforts.

Tokenizing is definitely the way to go for larger files. There isn't as much documentation on tokenization because the `.ne` compiler assumes no tokenizer (each character is a token!). It is not hard, however, to use the parser to parse an array of tokens, such as `[print, open_paren, "hello, world!", close_paren]`.

Splitting into individual sentences is also a good idea, but you need to be careful not to split things like

```
Transcript show: "This is some text. This is more text.".
Transcript show: (3.14 + 0.00)
```
incorrectly!

One thing you might want to check on is whether your grammar is ambiguous or not. Smalltalk, particularly, has this issue. `Cow makeSound: moo withLoudness: loud` can be naïvely parsed in two ways:

```Cow makeSound: (moo withLoudness: loud).
Cow makeSound: (moo) withLoudness: (loud).```

Ambiguous grammars are much slower to parse because nearley keeps track of all the different parsings.

How large are your test files? Can you share your grammar and tests?

I'm still very interested in getting "strict mode" working properly. If anyone here has some serious experience with using strict mode as an optimization technique, please weigh in. :-)

**Comment by ipelovski** [comment]
Wow, thank you for responding so quickly!

I have no problems with `Transcript show: "This is some text. This is more text.".`, since it is a job for the tokenizer to split it to correct tokens. What I get is `['Transcript', 'show:', '"This is some text. This is more text."', period]`. So this is a single sentence.

I'm 100% sure that my grammar is not ambiguous since my code throws an error if it founds more than one result from the Nearley parser :) Also I have no problem with code like `Cow makeSound: (moo) withLoudness: (loud).` because the parenthesis are obligatory in my grammar for this case :)

This weekend, if I'm not too lazy, I'll try to make a pull request with added `'use strict';` directive and to share some code with test results.

What results do you get from your grammars and test files?

**Comment by bobbybee** [comment]
@Hardmath123 What if we rewrote nearley as a fork of marpa, and ported it to JavaScript with node modules on the console and asmjs in the browser? Hehehehe

**Comment by ipelovski** [comment]
This weekend I decided to make some tests with and without the `'use strict';` directive. I used the sample `javascript.ne` grammar in the `examples` directory and the content of `lib/lint.js` file for input. The result is that I saw no difference in the time execution of the tests :) My explanation for the better times I get for my grammar is that either it is quite badly written, or because I use a lot of post-processing functions that are somehow sped up with the directive, or maybe both :)

**Comment by Hardmath123** [comment]
Wow, good to know. Did you add `'use strict';` to `nearleyc.js`, `nearley.js`, or the compiled `js` grammar file? I would expect the best results from strictifying `nearley.js`.

Also, the `javascript.ne` grammar is kind of outdated and weird (written by @JacobEdelman like a year ago). Maybe you should try using `nearley-language-bootstrapped.ne` (in `lib/`) with `nearley-language-bootstrapped.ne` as input? It's a bit meta, but it's ironically one of the best test cases we have. :-)

**Comment by bobbybee** [comment]
It's worth noting javascript.ne doesn't use preprocessors to the extent a normal nearley grammar would.

**Comment by Hardmath123** [comment]
Ah, yes, @bobbybee makes a good point here. This would be fixed by #33, so maybe we should prioritize that.

**Comment by ipelovski** [comment]
@Hardmath123, I first tried running the tests with `test/launch.sh` and it was then when I saw there is no difference in the execution time. Then I tried running `./bin/nearleyc.js ./lib/nearley-language-bootstrapped.ne` and got the same result (i.e. no difference).

>Wow, good to know. Did you add 'use strict'; to nearleyc.js, nearley.js, or the compiled js grammar file? I would expect the best results from strictifying nearley.js.

I added `'use strict';` to `nearley.js` and the compiled js grammar file.

**Comment by Hardmath123** [comment]
Awesome, @ipelovski, that's great to know.

I'm curious why the grammar in your initial post got faster when in strict mode. I imagine it might have used a postprocessor that was sped up by the strict mode optimizations. Let me know if you figure it out. :-)

**Comment by tjvr** [comment]
@Hardmath123 Is there any reason `nearleyc` doesn't output files with strict mode? :)

**Comment by Hardmath123** [comment]
How do you know the user's postprocessors are strict-mode compliant? I suppose it can be an option in `nearleyc`, but you could just put `@{% "use strict; "%}` at the top of your grammar, right?

**Comment by tjvr** [comment]
> How do you know the user's postprocessors are strict-mode compliant?

Oh dear. I somehow feel like we shouldn't have to ask this question in 2017, but I think that's just me wishing JS had somehow gotten better :P
