### ISSUE TITLE
Request: Add on-demand compilation like PEG.js' `buildParser` API

### ISSUE THREAD

**Issue by beaugunderson** [Hardmath123/nearley#78]
My workflow with PEG.js is to only ever use `.pegjs` files and to include them in node via PEG.js' `buildParser` API. I find this less error-prone than using generated JavaScript files (no wasted time debugging things and then realizing you forgot to regenerate after changing the grammar).

**Comment by Hardmath123** [comment]
While this might be helpful in development, it's pretty inefficient for production code (and won't work in the browser!). Also, for large projects, you probably have other stuff being compiled as well (LESS, Coffeescript, Jekyll, etc.). Overall, I'm not too keen on adding this feature.

While developing, I recommend using something like `$ watch nearleyc grammar.ne -o grammar.js &` instead (you might need to install `watch`). This automatically compiles the grammar every couple of seconds and has the added benefit of alerting you if there's an error in your parser as soon as you save from your editor!

**Comment by beaugunderson** [comment]
Fair enough; thanks the quick response!
