### ISSUE TITLE
Allow full unicode literals in strings

### ISSUE THREAD

**Issue by Hardmath123** [Hardmath123/nearley#83]
From @beaugunderson 

> another aside: it seems like the only way to include unicode literals (like
> \u2e03) is via a character class; is that intentional?

Note that for now, you can include the unicode literal, uh, "literally" like this:

`a -> "café"`

Alternatively, charclasses:

`a -> [\uxxxx]`

**Comment by Hardmath123** [comment]
Fixed in 21276503633fa7f6d24c6f51be0b108278314a3b.

**Comment by ffMathy** [comment]
@kach very cool, but how do we use this?
