### ISSUE TITLE
Spurious parses stemming from nullable nonterminals

### ISSUE THREAD

**Issue by corwin-of-amber** [Hardmath123/nearley#85]
The following grammar:
```
@builtin "whitespace.ne"

d -> a

a -> b _ "&"
   | b

b -> letter
   | "(" _ d _ ")"

letter -> [a-z]
```
when run using nearley-test on ```(x)```, generates two (identical) parses ```[ [ [ '(', null, [ [ [ [ 'x' ] ] ] ], null, ')' ] ] ]```. Since the above grammar is unambiguous, this is unexpected.

Notice that this does not occur if you omit the rule ```a -> b _ "&"```, which does not appear in the derivation, and this is even more unexpected. It has to do with the order of prediction.

I am preparing a pull request that suggests a fix.

**Comment by corwin-of-amber** [comment]
Tried 2.2.0 and it works :+1:

**Comment by Hardmath123** [comment]
Awesome. Closing, then.
