### ISSUE TITLE
npm run doesn't work on windows

### ISSUE THREAD

**Issue by steambap** [Hardmath123/nearley#91]
npm run bootstrap failed because there is no 'mv' command on windows.
npm test also failed. I think I need to build something with npm run bootstrap.

**Comment by Hardmath123** [comment]
Aha! Looks like you're our first Windows user. I haven't really paid attention to Windows since I don't have a Windows machine on which to test my changes.

If you have the time, do you think you could fix this? I think it's just a matter of rewriting `./build.sh` in Batch or some other Windows-compatible scripting language. You could even try rewriting it in Node and thus making the script platform-independent!

Thanks for reporting this!

**Comment by steambap** [comment]
thanks for reply. I'll try to see what's going on in build.sh and rewrite it in nodejs

**Comment by steambap** [comment]
I got another error when I try to run the 'npm run bootstrap' on cloud9 ide.

> steambap:~/workspace (master) $ npm run bootstrap
> 
> > nearley@2.4.0 bootstrap /home/ubuntu/workspace
> > node bin/nearleyc.js lib/nearley-language-bootstrapped.ne >lib/nearley-language-bootstrapped.js.new && mv lib/nearley-language-bootstrapped.js{.new,}
> 
> mv: missing destination file operand after ‘lib/nearley-language-bootstrapped.js{.new,}’
> Try 'mv --help' for more information.
> 
> npm ERR! Linux 4.2.0-c9
> npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/npm" "run" "bootstrap"
> npm ERR! node v4.4.0
> npm ERR! npm  v2.14.20
> npm ERR! code ELIFECYCLE
> npm ERR! nearley@2.4.0 bootstrap: `node bin/nearleyc.js lib/nearley-language-bootstrapped.ne >lib/nearley-language-bootstrapped.js.new && mv lib/nearley-language-bootstrapped.js{.new,}`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the nearley@2.4.0 bootstrap script 'node bin/nearleyc.js lib/nearley-language-bootstrapped.ne >lib/nearley-language-bootstrapped.js.new && mv lib/nearley-language-bootstrapped.js{.new,}'.
> npm ERR! This is most likely a problem with the nearley package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node bin/nearleyc.js lib/nearley-language-bootstrapped.ne >lib/nearley-language-bootstrapped.js.new && mv lib/nearley-language-bootstrapped.js{.new,}
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs nearley
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls nearley
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/workspace/npm-debug.log

**Comment by Hardmath123** [comment]
Ah, this is Cloud9 using a different shell version than I'm used to. In Bash, `file{.old,.new}` expands to `file.old file.new` automatically which is convenient for move instructions, etc. I guess that's not very portable though—I'll go fix that asap. Thanks for the bug report!

**Comment by Hardmath123** [comment]
Should be fixed by b3296b3 in v2.4.1.

**Comment by deltaidea** [comment]
Everything works on Windows right now. This can be closed.

**Comment by bd82** [comment]
In the future shx: https://github.com/shelljs/shx (portable shell commands package)

may assist with such issues.

**Comment by tjvr** [comment]
Thanks for confirming this @deltaidea! :D
