### ISSUE TITLE
Recording line numbers

### ISSUE THREAD

**Issue by solmsted** [Hardmath123/nearley#95]
Is there a way to have nearley provide line numbers in postprocessor functions and in parse error messages?  I'm aware that it provides the location index, which is useful, but I feel like line numbers (and columns) would be even more useful in many use cases.

**Comment by Hardmath123** [comment]
Yeah, I feel "line number" and "column number" is easy to derive given the location index, so this is a primitive you can write yourself and include with the `@{% … %}` syntax. Keep in mind that "line number" and "column number" aren't always well-defined; for example, if you're parsing a stream of non-characters or binary data.

**Comment by solmsted** [comment]
Thanks for your response.  To clarify, are you saying I could do something like `@{% var line = 1; %}` at the top of a grammar and then have a rule that matches newlines with a postprocessor that does `line += 1;`?  If that works I think that is satisfactory.  Is there any way to add that in addition to the offset property on caught exceptions?

**Comment by Hardmath123** [comment]
Ah, unfortunately that won't exactly work because postprocessors could be called multiple times for each input character. I would recommend keeping the string input in a separate variable and then doing something like `input.substring(0, offset).split("\n").length`.

**Comment by solmsted** [comment]
Hmm, that is unfortunate.  I was planning to set up a stream to do the parse in chunks, so the full input string won't be in memory.  However I would be able to search for '\n' in the chunks before passing them to parser.feed and try to maintain a map of offsets to line numbers.  Is there a way to pass that data in a way that it would be available to postprocessor functions within the grammar?

I noticed comments on #63 that mentioned using global variables to pass context; is there really no other way to share external data with postprocessor functions?  I don't think I can have the grammar file `require` something because it's dependent on the source file currently being parsed.

**Comment by matthew-dean** [comment]
What? No line / column numbers? PEGjs outputs the offset, line, and column for the start and end of the match. Is it the parsing method that makes it difficult in nearley?

**Comment by Hardmath123** [comment]
As I've said, you can trivially deduce line number from the token offset passed as input to the postprocessor. Nearley should not provide this functionality because it is domain-specific.

Alternatively, you can use a tokenizer that preserves lexical information. nearley now operates seamlessly with streams of arbitrary tokens, regardless of the presence of attached lexical information.
