### ISSUE TITLE
EOF token?

### ISSUE THREAD

**Issue by liam4** [Hardmath123/nearley#96]
I can't seem to figure out how to match an EOF.

https://github.com/Hardmath123/nearley/blob/b3296b31864f60b26237fddae522d18cac7cadc0/examples/javascript.ne#L283 implies that `<EOF>` used to exist..

```
#Program -> ( SourceElements )? <EOF> 
```

**Comment by liam4** [comment]
I fixed the issue I was having by slightly modifying my grammar definition, so I doubt this is actually needed..

**Comment by bobbybee** [comment]
That grammar was ported to nearley from another parser-generator, so don't infer to much meaning from it. Anyway, what would matching <EOF> semantically mean?!
